### ISSUE TITLE
WordPress database error

### ISSUE THREAD

**Issue by 6461766964** [LearnPress/LearnPress#10]
I received that message:

`WordPress database error: [Table 'rebeccadev.wp_users' doesn't exist]
SELECT um.* FROM wp_users u INNER JOIN wp_usermeta um ON um.user_id = u.ID AND um.meta_key = 'wp_capabilities' WHERE um.meta_value LIKE '%\"lpr_teacher\"%' LIMIT 0, 1`

Version: 1.0 & 0.9.19
Wordpress: 4.4.1

![screenshot from 2016-02-01 11 32 28](https://cloud.githubusercontent.com/assets/16630637/12718760/d4fb83c4-c8d7-11e5-8c7f-44384b690340.png)

**Comment by tunnhn** [comment]
That is a flaws of us by using a fixed table name, we will fix it soon ;)

**Comment by dkpyan** [comment]
I am experiencing the same issue. Any eta for when this will be fixed?

**Comment by ivanrojasorg** [comment]
I have wordpress 4.4.2 and WP_DEBUG activate

Then I install LearnPress WordPress LMS Plugin

When i Activate this plugin

The dashboard show this error

WordPress database error: [Table 'tdodbq960t.wp_users' doesn't exist]
SELECT um.* FROM wp_users u INNER JOIN wp_usermeta um ON um.user_id = u.ID AND um.meta_key = 'wp_capabilities' WHERE um.meta_value LIKE '%\"lpr_teacher\"%' LIMIT 0, 1

This is Screenshot
http://postimg.org/image/l03stalrh/

**Comment by ivanrojasorg** [comment]
<img src='http://s14.postimg.org/l03stalrh/Error_Learnpress.jpg' border='0' alt="Error Learnpress" />
