### ISSUE TITLE
Learnpress plugin version control

### ISSUE THREAD

**Issue by jonwheelerptc** [LearnPress/LearnPress#11]
Unclear whether version 0.9.19 is correct version of Learnpress to be using or 1.0. Our Wordpress install was upgraded to 1.0 but our other plugins are all older: 
LearnPress bbPress Integration Version 0.9.3 
LearnPress BuddyPress Integration Version 0.9.3
LearnPress Export/Import Courses Version 0.9.2

Also we are doing a fair amount of custom development of the templates and the underlying file structure between LearnPress 0.9.19 and 1.0 is significantly different so we aren't sure of which file structure to be developing on.

Appologies if this is wrong support channel to post to but had trouble creating account at https://thimpress.com/wp-login.php?action=register (no purchase code available for LearnPress)

**Comment by tunnhn** [comment]
We are working hard to upgrade LearnPress to 1.0 with a ton of changes and as you said it is more different with 0.9.x. So, you can develop on version 1.0 because we will release it in a nearest day. And of course, 0.9.x will be death.

You can post your question to get support from us here https://thimpress.com/forums/forum/plugins/learnpress/ but it maybe a bit slower than other topic with priority.

**Comment by jonwheelerptc** [comment]
Thank you Tu. I have tried to post questions on your Forum but without a
Purchase Code for Learnpress I cannot create an account to post questions.

We are working on a project that we need to finish by 28 Feb that relies on
both LearnPress and also the Buddy Press and bbPress LearnPress
integrations. Will 1.0 be released and working with new versions of those
plugins within the next few days? Otherwise I think we will have to just
develop on 0.9 which we know works with the plugins and perhaps upgrade
later.

Thank you.

Jon

On Wed, Feb 3, 2016 at 12:24 AM, Tu Nguyen <notifications@github.com> wrote:

> We are working hard to upgrade LearnPress to 1.0 with a ton of changes and
> as you said it is more different with 0.9.x. So, you can develop on version
> 1.0 because we will release it in a nearest day. And of course, 0.9.x will
> be death.
>
> You can post your question to get support from us here
> https://thimpress.com/forums/forum/plugins/learnpress/ but it maybe a bit
> slower than other topic with priority.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LearnPress/LearnPress/issues/11#issuecomment-178980130>
> .
>



-- 
Jon Wheeler
Partner | PowerThru Consulting
*Building movements, online and off -- for non-profits and campaigns*
p: 202-370-6144
e: jon@powerthruconsulting.com
w: www.powerthruconsulting.com
f: www.facebook.com/powerthruconsulting
t: twitter.com/power_thru
