### ISSUE TITLE
Certificates Does Not Appear in Learnpress Menu

### ISSUE THREAD

**Issue by steph-schoch-netbase** [LearnPress/LearnPress#115]
Hi:

I successfully installed and network activated (we have a multisite setup) Learnpress Certificates, but the **Certificates** item does not appear on the Learnpress menu. When I go to Learnpress -> Add-ons, it shows the Learnpress Certificates under Installed and its button reads **Disable Now**. If I click this button (with the intention of re-enabling the plug-in to see if that will change anything), I get the circular progress icon, but then it just goes back to Disable Now.

Any ideas?

**Comment by haihld58** [comment]
Hello steph-schoch-netbase,

Please sent me email with title "Learnpress - Certificates add-on" to hai@foobla.com . We will discuss more details about your issue and find solution for it.
