### ISSUE TITLE
404 Page when uses Polylang with Learnpress

### ISSUE THREAD

**Issue by worapongni** [LearnPress/LearnPress#123]
I used Polylang with Learnpress. After I created a new language (TH: Thai) page on Lesson. I got the link like this: http://www.xxxs.com/th/th/online-courses/something/yyy/lessons/zzz. It has two /th/, and makes my page to 404 page. How can I correct it?

Regards,
Worapong N.

**Comment by haihld58** [comment]
Hello worapongni,

Please contact develop team of Polylang plugin to try to find solution for your issue.
