### ISSUE TITLE
Single Course Permalink Issue

### ISSUE THREAD

**Issue by dandyxu** [LearnPress/LearnPress#125]
Hi, there

Thanks for developing such high quality of plugin and solve lots of issues for LMS in WordPress.

I just found an issue in recent update. The version of LearnPress is v2.1.2.

I found when I create a new lesson, the permalink becomes to the relative link, not like before, it's fixed link (begin with http://domainname.com). When this change happened, I just can't assign these lessons to courses anymore.

Can you check this issue and let me know whether it's something wrong specifically for my site or just plugin itself's issue?

Thank you very much and hope you have a good weekend.

Kind Regards,
Dandy

**Comment by sahrawat** [comment]
@dandyxu I think next update may take some time. Until then we will need to workaround. The instructor link is handelled by `public function get_instructor_html()` located inside "plugins/learnpress/inc/course
/abstract-lp-course.php" on line 473. You can just change the line `'<a href="%s">%s</a>',` to something like `'<a href="//example.com/members%s">%s</a>',`

**Comment by haihld58** [comment]
Hello dandyxu,

Learnpress doesn't support single lesson, quiz, question page, so you cannot directly access permalink as course. If you want  to view lesson content, you need access content of course what includes this lesson. 
You cannot assign a lesson/quiz to courses.

Please tell me more details about issue "When this change happened, I just can't assign these lessons to courses anymore." I try to change permalink of a lesson and it still assigned to a course.

**Comment by dandyxu** [comment]
Hi, Haihld58

Thanks for your reply and explanations. However, I already solved this issue by myself.

My solution is when I added new lessons in the course, I need to save this course first. Then I edit each lessons which have full permalinks. Then the issue I met before is solved perfectly. 

Just a little bit tricky.

Thank you anyway and hope you have a good day!

Kind Regards,
Dandy
