### ISSUE TITLE
learn_press_get_current_url() not working for non standard wp installations

### ISSUE THREAD

**Issue by krivinarius** [LearnPress/LearnPress#15]
When WordPress Address (URL) and Site Address (URL) in Settings/General are not the same and this happens when WordPress is installed in a separate folder (we are using Bedrock https://github.com/roots/bedrock) learn_press_get_current_url function is not returning the proper url and that causes your plugin to make too many redirects error. This happens when opening a quiz in a separate page.
You are using get_site_url() in lp-core-functions.php line 174. You should consider using get_home_url() instead because that one returns the url that is used on front.

**Comment by haihld58** [comment]
Hello krivinarius,

Learnpress 2.0.3 was released. Please check your issue in this version of plugin.

Thank you for your feedback!
