### ISSUE TITLE
Is there another repo for this plugin?

### ISSUE THREAD

**Issue by bynicolas** [LearnPress/LearnPress#161]
Is the github repo in sync with the WordPress plugins one?

I am facing missing functions since last update but on the github code, the function is still there in the file?

so what's the deal here?

**Comment by bynicolas** [comment]
I have to add that the last update to 2.1.5.1 ( from 2.1.4.2 ) broke my home page ( meaning the widgets are not showing up anymore )

I don't have any debug information so it's hard to see what is going wrong. So what changed exactly between the two versions.

Maybe update this repo with the changes?

Thanks

**Comment by bynicolas** [comment]
Ok, Found the other repo on [trac](https://plugins.trac.wordpress.org/browser/learnpress/).

you should definitely keep those 2 in sync! It's confusing!

Then I found the bug that broke my homepage.

you added a function in `inc/course/lp-course-functions.php` ([line 757-775](https://plugins.trac.wordpress.org/changeset/1620769/learnpress/trunk/inc/course/lp-course-functions.php?old=1606239&old_path=learnpress%2Ftrunk%2Finc%2Fcourse%2Flp-course-functions.php)) that messed up WordPress' template hierarchy.  

You're function needs to return the `$template` variable if not the result is unexpected behavior. Actually, my theme's `front-page.php` file was never loaded!

Actually, I'm not sure why you are using this hook if your never return/include any template file?

Here's what the function should look like. At least, not to break the templating process of WP. Maybe you should hook somewhere else like at [`wp`](https://codex.wordpress.org/Plugin_API/Action_Reference/wp) ?

	add_action( 'template_include', 'learn_press_prepare_archive_courses' );
	function learn_press_prepare_archive_courses( $template ) {
		global $wp_query;
		$query = !empty( LP()->wp_query ) ? LP()->wp_query : $wp_query;
		if ( !$query || !$query->is_main_query() ) {
			return $template;
			
		}
		if ( !empty( $query->posts ) ) {

			$ids = array();
			foreach ( $query->posts as $_post ) {
				$ids[] = $_post->ID;
				$_post = sanitize_post( $_post, 'raw' );
				wp_cache_add( $_post->ID, $_post, 'posts' );
			}
			_learn_press_get_courses_curriculum( $ids, false, false );
			_learn_press_count_users_enrolled_courses( $ids );
			//update_meta_cache( 'post', $ids );
		}

		return $template;

	}

**Comment by haihld58** [comment]
Oh, you consider the matter very carefully.

Thank you for your report. We realized and fix this problem. 

Best Regards
