### ISSUE TITLE
WooCommerce plugin:auto enroll option

### ISSUE THREAD

**Issue by aelsharawi** [LearnPress/learnpress#171]
there shall bee an identification for the product to be a digital download, so as purchase from woo commerce becomes auto-enrolled

**Comment by aelsharawi** [comment]
when a user purchase a course it is not auto enrolled

**Comment by aelsharawi** [comment]
-also when a guest (not logged in user) click on buy a course, it redirects him to a page of registration, after that redirects him to a the same page, the user expect to see payment page, instead he has to click on buy now button

**Comment by Luzelle** [comment]
I'm having the same issues. But I also have an issue that Microsoft Browsers won't let you log in. Anyone know anything about these issues and how to resolve them?
