### ISSUE TITLE
PHP 7.1 Issues

### ISSUE THREAD

**Issue by aelsharawi** [LearnPress/LearnPress#172]
FILE: `/home/nginx/domains/DOMAIN/public/wp-content/plugins/learnpress/inc/admin/includes/class-markdown-parse.php`

FOUND 2 ERRORS AND 2 WARNINGS AFFECTING 4 LINES

 ```
242 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 1694 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 2271 | ERROR   | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 2277 | ERROR   | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
```

FILE: `/home/nginx/domains/DOMAIN/public/wp-content/plugins/learnpress/inc/class-lp-page-controller.php`

FOUND 1 ERROR AFFECTING 1 LINE

 `209 | ERROR | 'clone' is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)`

**Comment by haihld58** [comment]
Hello aelsharawi,

Our developers checked but we did not see issue what you report on both nginx and apache. Please give me your site and admin account to hai@foobla.com . We will check it carefully and find solution of this issue.

Best Regards,

Lee

**Comment by phonglq** [comment]
Hi aelsharawi,

How can i got this issues? I setup a test site with nginx and php 7.1 but not get this issues.

Regards,
Phong

**Comment by aelsharawi** [comment]
this comes from a wordpress plugin

the plugin is 

PHP Compatibility Checker

**Comment by aelsharawi** [comment]
and this is a nginx error log

`2017/04/09 05:21:31 [error] 1297#1297: *1136 FastCGI sent in stderr: "PHP message: PHP Warning:  Declaration of WC_Product_LP_Course::get_price() should be compatible with WC_Product::get_price($context = 'view') in /home/nginx/domains/DOMAIN/public/wp-content/plugins/learnpress-woo-payment/incs/class-wc-product-lp-course.php on line 36" while  reading response header from upstream, client: 66.249.66.197, server: DOMAIN, request: "GET /educationwp/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "DOMAIN"`

**Comment by aelsharawi** [comment]
also there is

`client: 66.249.66.202, server: DOMAIN, request: "GET /wp-content/plugins/thim-framework/css/font-awesome.min.css?ver=4.7.2 HTTP/1.1", host`

**# Looks like it is the old framework still living somewhere**
