### ISSUE TITLE
Unable to load a course - learn-press-block-content

### ISSUE THREAD

**Issue by florianvp** [LearnPress/LearnPress#174]
Hello there,

First of all, congrats for your plugin, I left Moodle for your tools, thanks to your UX.
However, even if I'm not so bad on wordpress hacks, I don't find a way to make your plugin works.

I have tried Learnpress : 2.1.5.5, 2.1.5.4, 2.1.5.3, 2.0, 0.9 
With templates ( /templates moving to /learnpress includes) : Education Zone, eLearningWP, and Twenty 70
On several config : WP 4.7.3 and WP 4.6 french and english config ...
I'm working on Mac and try it on Safari, Chrome and Firefox

On all thats configs I have the same problem, when I'm enroll for a courses, I get the interface which is loading, but I'm bloqued by the learn-press-block-content div turning and not loading the course, in the background, In function of config, I can see a 404 error, or the homepage, or sometimes the courses (on 2.0 version) but I never can access to it.

Online access : http://vps347943.ovh.net/wplearn/index.php/lp-courses/
with testeur/testeur for enroll.

I'm ok to change theme, WP version, LP version, I just want to make it works :)

Could you help me please ?

Best,

Florian.

**Comment by bynicolas** [comment]
Just a taught, have you tried resaving the permalink to make sure it's not a rewrite rule issue?

**Comment by florianvp** [comment]
Thanks for your answer @bynicolas I have tried to look in that way, but honestly I'm not very good on this. I'm agree with you, it look like if courses are unreachable.
I've read somewhere thats the course's direct url aren't directy reachable, is it true ? Because it was the case for me. 

My WP permalink are on : 
<img width="844" alt="wp" src="https://cloud.githubusercontent.com/assets/4622486/24505138/1feaf8dc-1559-11e7-99a0-393dd652420a.png">

My LP permalink are on : 
<img width="710" alt="learnpress" src="https://cloud.githubusercontent.com/assets/4622486/24505137/1fc595e2-1559-11e7-92aa-a8a0ec2a1e92.png">

And there is my .htaccess 


# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /wplearn/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /wplearn/index.php [L]
</IfModule>

# END WordPress

Do you see anything wrong ?

Thanks,

Florian.

**Comment by bynicolas** [comment]
I don't know what you read about the course direct url being directly reachable.  I assume they can't be directly accessed since they need some kind of authentication.

Again, I'm not one of the developer of the plugin, but I noticed in your permalink structure you have `/index.php/%postname%/%year%/%monthnum%/%day%`. Try removing `/index.php` from that setting and see if it helps.

**Comment by florianvp** [comment]
Thanks a lot for you answer @bynicolas the problem was really permalinks. I have change WP permalinks to %postname% and it broken everything so i have searched on this way, and after some mod_rewrite, some .htaccess and change my apache2.conf ... here we are : it works !!!

🥇 for you :)

Thanks a lot,

FloriaN.
