### ISSUE TITLE
Feature request: sell the course collection

### ISSUE THREAD

**Issue by aelsharawi** [LearnPress/learnpress#175]
Hi

can we put an option to sell the course collections.

**Comment by bynicolas** [comment]
I think all ecommerce logic should not be included within learnpress but rather use a proven ecommerce solution and link both learnpress with the ecommerce solution via a plugin. I think the most popular WooCommerce or EasyDigitalDownload should be connected/integrated to learnpress

**Comment by digistork** [comment]
Thank you aelsharawi. This is a STRATEGICAL point. Since a collection MAY NOT have the same price as the sum of individual courses, and as other LMS do. 

And THEN using some woocommerce or other third party to checkout.

Any ETA on that ?
