### ISSUE TITLE
Trying to get property of non object

### ISSUE THREAD

**Issue by bynicolas** [LearnPress/LearnPress#180]
This happens when a user is logged in. Introduced in 2.1.5 ( when I first start to see this in the logs)

    Notice: Trying to get property of non-object in /var/www/stage.example.com/htdocs/wp-content/plugins/learnpress/inc/class-lp-query.php on line 135

**Comment by tutv95** [comment]
Hi @bynicolas,

You can update the LearnPress plugin to the latest version and check it again.
And let me know if it still failed.

Regards,
Max
