### ISSUE TITLE
is_single was called incorrectly

### ISSUE THREAD

**Issue by bynicolas** [LearnPress/LearnPress#181]
This happens when a user is logged in. Introduced in 2.1.5 (at least it's when I first noticed it)

    Notice: is_single was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /var/www/stage.simplywp.co/htdocs/wp-includes/functions.php on line 4137

**Comment by tutv95** [comment]
Hi bynicolas,

Please switch to a default theme ([Twenty Sixteen](https://wordpress.org/themes/twentysixteen/)). And check it again.

Regards,
Max
