### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by tnoguero** [LearnPress/LearnPress#19]
I have installed the plugin and create a course with lessons. But everytime I try to access the course it says page not found. 
The courses has a base page which i can access. That page list all the available courses. When clicking on one it gives me the page not found. If I try to access directly from the url on the configuration page of the course I get the same error. What I am doing wrong?

**Comment by tnoguero** [comment]
Hi

Some more information about the issue. 
1) when i created the lessons and courses the site had a different ip that i had changed recently. I realized of this by looking on the guid column of the records. I deleted my courses and lessons and created them again.
2) when i use permalink it doesn't work, i get the same 404 error. When i change it back to not using pemalink it works, but I would like to use them, Any idea of how to solve this?

Thanks

**Comment by haihld58** [comment]
Hello tnoguero,

Learnpress 2.0.3 was released. Please check your issue in this version of plugin.

Thank you for your feedback!

**Comment by wajeehAfridi** [comment]
> I have installed the plugin and create a course with lessons. But everytime I try to access the course it says page not found.
> The courses has a base page which i can access. That page list all the available courses. When clicking on one it gives me the page not found. If I try to access directly from the url on the configuration page of the course I get the same error. What I am doing wrong?

I did just update the permalink setting and the issue got solved, change settings to plain or else don't keep plan.

**Comment by wajeehAfridi** [comment]
I did just update the permalink setting and the issue got solved, change settings to plain or else don't keep plan.
