### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by rainerborene** [LearnPress/LearnPress#196]
I've just installed LearnPress plugin successfully. But I'm getting a blank page. What's the first step to debug it?

See it here: https://personalmamaebebe.com/curso/online/

**Comment by tutv95** [comment]
Hi @rainerborene,

Please enabled the [debugging on Wordpress](https://codex.wordpress.org/Debugging_in_WordPress). Then you can know where the reason came from.

Regards,
Max
