### ISSUE TITLE
enroll-button.php

### ISSUE THREAD

**Issue by ajayshrivas** [LearnPress/LearnPress#197]
Notice: learn_press_get_template was called incorrectly. /home/hostingsitesco/public_html/developer18/weding/wp-content/plugins/learnpress/templates/single-course/enroll-button.php does not exist. Please see Debugging in WordPress for more information. (This message was added in version 2.1.) in /home/hostingsitesco/public_html/developer18/weding/wp-includes/functions.php on line 4139

**Comment by tutv95** [comment]
Dear @ajayshrivas,

The plugin has not used template `single-course/enroll-button.php` anymore. Please update the theme to compatible with the LearnPress latest version.

Regards,
Max

**Comment by ajayshrivas** [comment]
Hello,

Thanks for you replay i have been working on theme update and all template
add new but courses single page in wordpress debug true time give error.


Thanks
