### ISSUE TITLE
Problem with lessons: url not found

### ISSUE THREAD

**Issue by tedc** [LearnPress/LearnPress#202]
Hi, I'm having some problems with the ajax call for the lessons. When I click on an item, the url is converted from http://mydomain.com/course/sample-course/lessons/sample-lesson/ to http://mydomain.com/wp/http://mydomain.com/course/sample-course/lessons/sample-lesson/ and I can't find any solutions for this issue. I'm using Bedrock https://github.com/roots/bedrock, that works with different urls for WordPress Address (mydomain.com/wp) and Site Address (mydomain.com).

**Comment by tutv95** [comment]
Hi @tedc,

Have you tested it with the default theme and with only LearnPress yet?

Regards,
Max

**Comment by tedc** [comment]
Nope, but I found the source of this issue (not its solution, yet).
In the single-course.js file we have this:
`
				var val = Course_Item.__super__.get.apply(this, arguments);
				if (arguments[0] == 'url') {
					val = LP_Course_Params.root_url + val;
				}
				return val;
			},
`
and the LP_Course_Params are
`var LP_Course_Params = {"root_url":"http:\/\/uba.dnative.com\/wp\/","id":5428,"url":"http:\/\/uba.dnative.com\/corsi\/learnpress-101\/","results":0,"grade":"in-progress","grade_html":"In Progress","current_item":5238,"items":[{"id":5254,"type":"lp_lesson","title":"Adding Columns at Breakpoints","section_id":3,"url":"http:\/\/uba.dnative.com\/corsi\/learnpress-101\/lezioni\/adding-columns-at-breakpoints\/","status":"viewed"},{"id":5083,"type":"lp_lesson","title":"Applying CSS","section_id":3,"url":"http:\/\/uba.dnative.com\/corsi\/learnpress-101\/lezioni\/applying-css\/","status":""},{"id":5240,"type":"lp_lesson","title":"Build Your Own Function Part 3 - Total Automation with Lists","section_id":3,"url":"http:\/\/uba.dnative.com\/corsi\/learnpress-101\/lezioni\/build-your-own-function-part-3-total-automation-with-lists\/","status":""},{"id":5238,"type":"lp_lesson","title":"Build Your Own Functions","section_id":3,"url":"http:\/\/uba.dnative.com\/corsi\/learnpress-101\/lezioni\/build-your-own-functions\/","status":"viewed"}]};`
So root_url + url = http://uba.dnative.com/wp/http://uba.dnative.com/corsi/learnpress-101/lezioni/applying-css/, like I said in the previous comment.

**Comment by tedc** [comment]
This error is given by the use of get_site_url() in the public functions output_args and get_items_params of LP_Abstract_Course. I think that it's better to use get_home_url() in the place of get_site_url()
