### ISSUE TITLE
Can only create question as True/False

### ISSUE THREAD

**Issue by StageCoachDriver** [LearnPress/LearnPress#21]
When I try to create a new question from the Question screen, I can only create a True/False. If I try to change the question type the screen is greyed out and I'm asked if I really want to change the question type. There is no response box and I can only return to the previous screen.

WP version 4.5.2

![capture](https://cloud.githubusercontent.com/assets/5447964/15637139/ed12e71c-25c6-11e6-8604-07180135b1c8.PNG)

**Comment by haihld58** [comment]
Hello StageCoachDriver,,

Learnpress 2.0.3 was released. Please check your issue in this version of plugin.

Thank you for your feedback!
