### ISSUE TITLE
Quiz Retake Issue

### ISSUE THREAD

**Issue by jsmarketing** [LearnPress/learnpress#216]
Hi.

We saw this issue previously, which seemed to fix itself, in a progressive update. But it has since returned.

When a user fails a quiz and clicks retake, it keeps refreshing the page and saying failed. Then just adds a failed attempt in the database with 0 questions answered.

Any ideas?

Thanks

J

**Comment by nickwilliamsnewby** [comment]
what version of learnpress is it?

**Comment by smartie19889** [comment]
This is on version 2.1.9.3
