### ISSUE TITLE
LearnPress lessons just flashes?

### ISSUE THREAD

**Issue by nordsec** [LearnPress/LearnPress#22]
Hi..

Great product, but i bit thin on documentation..

Techsofen.com is my site (maintenance mode)

The problem when i try to start a lesson the lesson comes up but just with a flash of the page with the lesson banner from learpress placed in the midle of the screen.. only thing i can do is to close the lesson?

src="https://cloud.githubusercontent.com/assets/11534222/16706507/da3d8ddc-45af-11e6-9276-439b8dc7ea28.png">

Best from
Frode

**Comment by haihld58** [comment]
Hello nordsec,,

Learnpress 2.0.3 was released. Please check your issue in this version of plugin.

Thank you for your feedback!
