### ISSUE TITLE
Learnpress Rest API integration

### ISSUE THREAD

**Issue by saalmaan** [LearnPress/learnpress#231]
Great plugin and almost perfect.

I am building SPA and need access to courses/lessons/question... via REST API but unfortunately, it looks like Learnpress is not compatible with WordPress REST API.

Question: is there a plan to support REST API? if yes then by when?

Many thanks
Salman

**Comment by rslonik** [comment]
Someone started working on that
https://github.com/LearnPress/learnpress/pull/243

**Comment by saalmaan** [comment]
exciting, can't wait. 👍

**Comment by elron** [comment]
Awesome. Looking forward to it

**Comment by dantn93** [comment]
Hi there, is there any api? When do you finish it?

**Comment by AdamGniady** [comment]
Hey guys. Great Application, thanks for that!
Are there any news about the WordPress REST API integration for LearnPress? Would be a blast!

**Comment by jaydeepgiri** [comment]
@rslonik Hey Bro I've added this #243 in my code. path for this file is mydomain.com/wp-content/plugins/learnpress/inc/api/class-lp-api.php, but now my question is how to access this API? What would be the endpoint or URL to Access this API? I'm bit confused. 
Thanks

**Comment by merahul31** [comment]
Is there any update? I am still not able to get the APIs

**Comment by tungnxt89** [comment]
Hi @all,

We has provide some api. You can view code on folder "inc/rest-api/v1/". This is exxample: wp-json/lp/v1/courses/archive-course?return_type=json

When we done Doc API, we will public and provide for you.

Thanks.
