### ISSUE TITLE
learnpress 3.0.5 lesson preview bugs

### ISSUE THREAD

**Issue by isaacping** [LearnPress/learnpress#239]
Since the last update to learnpress 3.0.5, when the “Preview” checkbox is checked for a lesson, it gives an error in the curriculum section: Notice: Undefined property: LP_Lesson::$get_item_type in xxxxx\wp-content\themes\eduma\learnpress-v3\single-course\section\item-meta.php on line 23 etc..

![cerrors](https://user-images.githubusercontent.com/37938177/38146811-9ea6be02-341d-11e8-94d1-31b74ce77b5f.JPG)

**Comment by nickwilliamsnewby** [comment]
this appears to be a theme specific error may be better suited for that repo
