### ISSUE TITLE
LP 3.0.5 Error: Permalink only available if the item is already assigned to a course.

### ISSUE THREAD

**Issue by Ermejo75** [LearnPress/learnpress#240]
Hi 

I am getting this error with the new update of LP
When I create a new course, sections and lessons, it's impossible to save the course.
Lessons disappear from the Curriculum once I save, and cannot make changes to the Section Titles.

If I go in a lesson I see that although it's assigned to a course there's no permalink
Error: Permalink only available if the item is already assigned to a course.
![lp_lessons_no_link](https://user-images.githubusercontent.com/38033041/38239012-eaeb5e4c-372b-11e8-8905-f330ea318a31.png)

What to do?

Regards

Antonio

**Comment by nickwilliamsnewby** [comment]
are you using the latest version? can you outline some steps to reproduce like this (example):
>create course
>add lessons,sections on course page
>hit save
>loose the content that was added 
also is that an accurate description in my example?

**Comment by Ermejo75** [comment]
Hi Nick

Everything is on the latest version, LP, WP. Php...
I tried 2 different Themes, Course Builder (ThimPress) & Generate Press but it's the same thing

I create a new course (but it's the same with older courses)
add lesson & sections, hit save but the content it's not saved
and lessons created disappear from the curriculum

I then see that In Dashboard > LearnPress > Lessons
the Lessons I created are there but appears like I showed you in the image without a permalink

If I change Sections or Lessons Title it doesn't save
If I try to duplicate an older lesson doesn't allow me to change the link

Any insights?

Regards

Antonio

**Comment by nickwilliamsnewby** [comment]
Is the site live and can you access the site via ftp? If so edit the wp-config.php file to so that debugging is set to true, then retrace your steps taking screen shots of any errors that show up, have you edited the theme with any custom code?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ermejo75** [comment]
Hi Nick

I did set to true the Debug in Config.php 
In this short video are the steps I followed and the problems I'm experiencing https://youtu.be/7NboOXOk7Ns

Hope you can help 

Regards

Antonio

**Comment by elichika85** [comment]
Hi Antonio! 
Have you already fixed this problem with the permalink? I´m having the same problem and I can´t solve it. 
Thanks in advance!
Eli
