### ISSUE TITLE
course-item-content-header on Safari

### ISSUE THREAD

**Issue by fabiograsso** [LearnPress/learnpress#242]
Hello,
it seems that Safari doesn’t render fine course-item-content-header.

Instead of displaying the bar with the name of the course, the search and the full screen button, you can see the page of the theme below.

I was in doubt that it could be due to my personalization, so I tried on a brand-new WordPress setup with a basic theme (Twenty Eleven) and I get the same result. I have tried with various themes and in all cases on Safari I don’t see correctly the top bar when look at the lessons.

I’ve tried to play with CSS and z-index values but with no luck.

i attach an example on Safari (wrong):
![safari](https://user-images.githubusercontent.com/798097/38245127-38263798-373d-11e8-827d-bd16ea63fd6b.png)
and on Chrome (correct):  
![chrome](https://user-images.githubusercontent.com/798097/38245128-384904c6-373d-11e8-9cf7-498fd2d3dc62.png) 

The issue is present on bot Mac OS and iOS

can you verify?

Thank you

**Comment by nickwilliamsnewby** [comment]
It's hard to tell on mobile it looks like a margin setting that isn't working correctly, you played with this?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fabiograsso** [comment]
Hello Nick, it doesn't seem a margin problem.

The same issue is present also on Safari for MacOS, so it's not just a mobile issue. I think that's something related on how Safari handle css

**Comment by Psmeg** [comment]
Has anyone found a solution to this problem?
