### ISSUE TITLE
Certificates unable to download or print

### ISSUE THREAD

**Issue by fitbodywrapadmin** [LearnPress/LearnPress#26]
We purchased the Certificates addon for our LearnPress plugin and are having some difficulty getting it to work. Once a course is completed and the user clicks the “View Certificate” button on the course page it opens the Certificate Preview window and when you try to click either of the image links to download it does nothing. When they try to print it opens the print window however it does not show the Certificate alone it shows part of the certificate along with the background showing the website behind it.

Running JS Debug with Chrome states that AJAX URL not defined in certificates.js.

This file has not been modified in any way after setup so I am unsure as to why it is saying that. I added a function to the learnpress-certificates.php file to fix this but now am getting this error:

cert_url is not defined on line 145 of certificates.js

I see that this appears to be defined in cert-preview.php but am unsure why it is not working.

I have no idea why it will not print, the only thing I can figure is that the canvas is not converting to am image prior to printing during the preview process.

Our LearnPress install is set to go live any day as we are adding content as we speak and I need to get this resolved ASAP if you could help out, thanks.

Also trying to right click and copy or save the image results in a black image being saved or pasted with no certificate. Thanks

**Comment by TheBankTrader** [comment]
I have the same problem. 
Is there any solution yet?

**Comment by haihld58** [comment]
Hello,,

Learnpress 2.0.3 was released. Please check your issue in this version of plugin.

Thank you for your feedback!
