### ISSUE TITLE
LPglobalsettings.localize.button_ok

### ISSUE THREAD

**Issue by Raminsouli** [LearnPress/learnpress#281]
Hi guys, 
We have LP since a long time, we have around 80 courses on.
Today, out of a sudden the website is not loading (www.entrepreneurslb.academy) is not loading.
Upon chrome inspect, the console gives an error on file global.js :1207

$.alerts.okButton = lpGlobalSettings.localize.button_ok

when we deactivated the 'LearnPress' plugin, the site was able to launch to the Eduma theme.
When we reactivated the 'LearnPress' plugin, the site halts on the above mentioned error.

please help.
the site is live but needs to be in production very soon

Eduma version: 3.2.1
LearnPress version: 3.0.9
NB: we installed LP bbPress, LP Course Review, LP Course wishlist, and they were all working fine; the site does not launch with LearnPress even if all those extensions are disabled.

Should I uninstall/reinstall , I don't want to loose all the courses that has been uploaded...

thanks

**Comment by frunncisco** [comment]
Hi, I'm experiencing something similar.
I'm on Course Builder theme by thimpress
Tried LearnPress version: 3.0.9 and 3.1.0

Site is loading correctly except course pages where I can see the js error below
`Uncaught ReferenceError: lpGlobalSettings is not defined
    at HTMLDocument.<anonymous> (global.js:1207)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
    at HTMLDocument.K (jquery.js:2)`

Hope someone helps

**Comment by callmewhy** [comment]
same problem

**Comment by Jhos-duall** [comment]
Hi people, i resolve this problem going to the file /wp-content/plugins/learnpress/assets/js/glogal.js
comment this lines (1207 and 1208) and add a code to hide the preloader.

this work for me.
`// $.alerts.okButton = lpGlobalSettings.localize.button_ok;
            // $.alerts.cancelButton = lpGlobalSettings.localize.button_cancel;

            var explode = function(){
                
                $('#preloader').fadeOut( "slow" );
            };
            setTimeout(explode, 2000);`

**Comment by mariaferraro** [comment]
I've got the same problem and that solution only remove the error but doesn't solve it. Checkout page doesn't go further...

**Comment by elharony** [comment]
@Jhos-duall Thanks for your solution!

**Comment by elharony** [comment]
@Jhos-duall Thanks for your solution, it works! 👍

**Comment by elharony** [comment]
@Jhos-duall Thanks for your solution, it works! 💯
