### ISSUE TITLE
Assign lesson to course UI broken

### ISSUE THREAD

**Issue by leonp** [LearnPress/learnpress#286]
User wants to assign a lesson to course. Expected process:

1. Create course
2. Create lesson
3. Assign lesson to course using 'Assign' dialogue

The actual process:
1. Create course
2. Create lesson
3. Select 'Curriculum'
4. Create a new 'Curriculum' (there's no indication what a curriculum is)
5. Give it a random name
6. This reveals a list of course
7. Assign courses to curriculum

Took hours' research to find this. Completely unintuitive.

**Comment by yinkosreal** [comment]
Please, can you expatiate on this? I installed the plugin but can't find the tool to assigned
