### ISSUE TITLE
xAPI, SCORM content integration

### ISSUE THREAD

**Issue by Aelkeris** [LearnPress/LearnPress#29]
I have a question regarding xAPI and SCORM content integration and support. 
Does LearnPress support content made by third party tools, which are xAPI and SCORM compliant ?

**Comment by haihld58** [comment]
Hello Aelkeris,

Currently, Learnpress doesn't support xAPI, SCORM content. Our developers will check and consider your suggestion.

Best Regards,

Lee

**Comment by Ben-Jamin** [comment]
Hi Lee, 

I am new to LearnPress and from what I have read it is now Scorm compliant is this true?

Regards 
Ben
