### ISSUE TITLE
Lesson permalink broken/page not found?

### ISSUE THREAD

**Issue by ayla484** [LearnPress/learnpress#312]
I am using LearnPress 3.2.2. I created a course and added sections in the Course Curriculum. I have created lessons and it looks good; but, when I click on the permalink or go in to the course (as creator and a student) and click on the lesson, it says, "Oops! Page not Found."

Please help!

**Comment by Yasirhussainkhaskheli** [comment]
you can assign student directly in the course section when you chose  a course and lesson it does not match requirements because LearnPress do not provide many functionalities like excel import export and many more issue when you customize this plugin
