### ISSUE TITLE
LearnPress 2.0 auto enroll not working

### ISSUE THREAD

**Issue by rslonik** [LearnPress/LearnPress#32]
Tested with LP 1.0.8 against LP 2.0. Auto enroll feature stoped working.

With or without Eduma Theme.

**Comment by rslonik** [comment]
up?

**Comment by haihld58** [comment]
Hello rslonik,

Learnpress 2.0.3 was released. Please check your issue in this version of plugin.

I'm looking to hearing from you.

**Comment by rslonik** [comment]
Created a fresh WordPress install with Learnpress 2.0.4

When I try to create a Course, I get the error reported in Issue #40

**Comment by haihld58** [comment]
Hello rslonik,

Please update Learnpress 2.0.9 and check this issue again. Our developers checked and resolved it in the latest version.
