### ISSUE TITLE
After updating the Learnpress 2.0, uploaded courses and homepage not displaying

### ISSUE THREAD

**Issue by abhishekonair** [LearnPress/LearnPress#33]
After plugin update to Learnpress 2.0 the homepage and course page still not displaying. it only showing the inner-loading icon. But when it checked the customized page it working fine.

Link: transformitlearning.com

Course example page: http://transformitlearning.com/course/symantec-endpoint-protection-12-x-sc1433/

Customized page(working): http://transformitlearning.com/symantec-training-in-bangalore/ @halink0803 @getmanzooronline

**Comment by rslonik** [comment]
Do you have access to your server logs? You should see there for the error.

Paste last few lines of logs content here if you need help.

**Comment by abhishekonair** [comment]
i dont know where to get from the directory

**Comment by haihld58** [comment]
Hello everyone,

Learnpress 2.0.3 was released. Please check your issue in this version of plugin.
