### ISSUE TITLE
Please keep the library clean: LPRequest

### ISSUE THREAD

**Issue by vollyimnetz** [LearnPress/learnpress#345]
Hi there,
you are adding the function 'LPRequest' to "Vue.http" which might be OK if you are not on an multi-plugin-system (but you are). So every plugin that includes vue after your plugin will override your custom function, which leads to an error (i.e. with my Plugin: https://wordpress.org/support/topic/%D1%81onflict-with-learnpress-plugin/).

I would recommend the following:
Exclude your LPRequest (and all possible further extensions of the vue-class) in an unique, seperate helper class/function so you can access it from everywhere.

Also, your vue.js and your vue.min.js are different versions.

**Comment by tunnhn** [comment]
Ok, thank you! We will review and update our plugin
