### ISSUE TITLE
'wp-content' hardcoded all over the plugin

### ISSUE THREAD

**Issue by krivinarius** [LearnPress/LearnPress#35]
Please be aware that many WordPress installations do not use wp-content folder for themes and plugins.
The way you hardcode this is very amateurish. There are many ways to get the path/url of the plugin like plugin_dir_path( dirname( __FILE__ ) ) and plugin_dir_url( __FILE__ ) 

You should consider doing it that way.

**Comment by haihld58** [comment]
Hello krivinarius,

Thank you for your feedback. Our developers will check and resolve this issue in the next version of plugin.

Regards,

Lee
