### ISSUE TITLE
Unable to add the same lesson to multiple courses

### ISSUE THREAD

**Issue by ullfindsmit** [LearnPress/learnpress#353]
I have a couple of lessons that are the same across courses. 
Unable to use the same lesson once its assigned to a course, even though its supported in the database schema.

**Comment by tunnhn** [comment]
Sorry! Currently, for some reasons it does not allow to assign a lesson (or quiz or any item under course) to multiple courses.

**Comment by ullfindsmit** [comment]
Check out this commit
https://github.com/ullfindsmit/learnpress/commit/59cc96535a2ff39e0f8a5e26c26cf5ee4505014d

I added logic so when searching you can assign the same lesson to multiple courses if you search but by default it only shows unassigned courses.

**Comment by xeydod** [comment]
@ullfindsmit I did something similar, but the problem now:
1. add the lesson to course A
2. add the lesson to course B
3. lesson is removed from lesson A

Couldn't find a solution for that.

**Comment by ullfindsmit** [comment]
I ran into that one too
This commit [https://github.com/ullfindsmit/learnpress/commit/f8f291cd06fdb1b5201388ad12da35c430f6ef25](url) 

Fixes that issue

**Comment by xeydod** [comment]
@ullfindsmit is says "No results matched your search."

**Comment by ullfindsmit** [comment]
Lets try this one

[`https://github.com/LearnPress/learnpress/pull/352`](https://github.com/LearnPress/learnpress/pull/352)
