### ISSUE TITLE
Unable to run learnPress wizard 

### ISSUE THREAD

**Issue by Chamyd** [LearnPress/learnpress#361]
I was able to download the LearnPress plugin but, the setup wizard will not run.
When I click to run it just goes to a blank page. I am using oceanWP theme
can someone please help me with his issue?

**Comment by kimhf** [comment]
I have a similar issue. There are cases where the setup wizard notice will show without the user actually being able to complete it or even show it. For example current user needs to be able to install_plugins, this is disabled for everyone on the project I'm working on, so it is not possible to complete the setup wizard.
