### ISSUE TITLE
No cart seems to be present

### ISSUE THREAD

**Issue by Just-m** [LearnPress/LearnPress#37]
Not sure how this plugin should work but after installing the plugin and creating a course, the only thing I see on the frontend is the course and a button to enroll. Clicking enroll, shows a login screen.

I expected the course to be added to a cart/checkout to gather student information and payment.

**Comment by rslonik** [comment]
There is a bug with the model. Find and modify the lp-profile page, include the Thim Login Form (with Visual Composer). Now, the "register" action will work.

**Comment by haihld58** [comment]
Hello Just-m and rslonik,

Please update Learnpress 2.0.9 and check this issue again. 

With any issue of Education WordPress Theme | Education WP, please post you topic in our support forums, our supporters will check and find solution of your issue. https://thimpress.com/forums/forum/eduma/
