### ISSUE TITLE
pagination when courses is homepage

### ISSUE THREAD

**Issue by jimyaghi** [LearnPress/learnpress#376]
When using the courses (static) page as the website's homepage, pagination does not work correctly. I think this is because on the homepage the pagination query variable should be "paged" instead of "page". i spent all day trying to track it down and now that i have, i don't really know how to fix it. Wordpress overwrites the "page" query variable and it does not paginate. This ONLY happens when the courses page is assigned to the site homepage, and only when accessed from the homepage rather than the courses URL.

so for example,

http://example.com/courses/2 ( works )
http://example.com/courses    ( works )

http://example.com/  (works)
http://example.com/2   (does not work - it shows page 1 despite thinking it's on page 2)

**Comment by gerolu** [comment]
Hi!
Did you solve it?
Or creator?

**Comment by jimyaghi** [comment]
I don't know if it ever got solved but I left this system because it was
very poorly written and slow. I'm now using sensei lms. As it turns out
learn press is built by butchering together woocommerce and senseilms to
make this monstrosity that's too slow.

**Comment by gerolu** [comment]
Дякую за листа!
Спасибо за письмо!
Thanks for your letter!

**Comment by gerolu** [comment]
Thanks for your reply!
May I look to your website with that sensei lms? Just to have a look)

**Comment by azamansagor** [comment]
I am also having the same issue. It's not solved yet.

**Comment by gerolu** [comment]
Дякую за листа!
Спасибо за письмо!
Thanks for your letter!

**Comment by gerolu** [comment]
Дякую за листа!
Спасибо за письмо!
Thanks for your letter!
