### ISSUE TITLE
Issue with Page Builder and SiteOrigin

### ISSUE THREAD

**Issue by nicomrios** [LearnPress/LearnPress#38]
![sin titulo](https://cloud.githubusercontent.com/assets/10748239/20332822/59e4411e-ab8d-11e6-9854-04ee1fc0877c.jpeg)
Hi, got a problem with LearnPress. After the last update, Page Builder doesn't work anymore, and i get the visual editor only, causing my homepage stop loading. 
If i deactivate LearnPress from the plugins, everything goes back to normal.
anyone with a similar issue?

**Comment by chrismcmullan** [comment]
I have a similar problem and yes I have Page Builder and SiteOrigin but the problem of the site not load seem to not work with Slider Revolution plugin which launch  on my home page.  I am using the theme Education WordPress Theme | Education WP.  I am going back to the theme developer as well.  If I deactivate the LearnPress plugin the home page will load

**Comment by nicomrios** [comment]
Just update to Learnpress 2.0.4, and nothing, still the same.

**Comment by haihld58** [comment]
Hello nicomrios and chrismcmullan,

Please update Learnpress 2.0.9 and check this issue again. Our developers checked and make sure our plugin compatibility with SiteOrigin page builder. http://prntscr.com/donuvg

With any issue of Education WordPress Theme | Education WP, please post you topic in our support forums, our supporters will check and find solution of your issue.
