### ISSUE TITLE
"Duplicate this course" not working

### ISSUE THREAD

**Issue by rslonik** [LearnPress/LearnPress#39]
I've commented directly in the commit. Can you help me on this, @tunnhn ?

https://github.com/LearnPress/LearnPress/commit/a757b14202164b250678401bf8cccefea18afdfe#commitcomment-19833242

The problem is that `page_row_actions` filter is evaluated only for hierarchical posts. My question on this is: can I change the Course CPT back to hierarchical? (and possible do a PR to fix this issue?)

**Comment by haihld58** [comment]
Hello rslonik,

This issue was resolved in latest version of Learnpress. Please check it again.
