### ISSUE TITLE
I have Just installed and getting 404 pages

### ISSUE THREAD

**Issue by SteveBillett** [LearnPress/learnpress#402]
I have just installed Learnpress on to a vanilla wordpress site and only get 404 pages on the courses and lessons.  I am running 7.3 php and the latest version of Wordpress.

I have loaded your test data and its the same.

Please advise what i am doing wrong.

**Comment by JusticeBringer** [comment]
Just move to LearnDash or TutorLMS.

**Comment by amanullahtanweer** [comment]
Please check if you have permalinks enabled. It might be because if of that.
