### ISSUE TITLE
Course Preview Loading Error

### ISSUE THREAD

**Issue by m-imran79** [LearnPress/LearnPress#41]
Hello,

I created a sample course and then added dummy lesson which is visible to everyone. On the front end, when visitor clicks on Course Curriculum, and then press Preview button, nothing happens and if you click on the lesson, it opens new page which shows continues loading circle which does not goes away.

Please click on the link below then select the Course and then click on any lesson to see the error. Further, any options in that screen like ” < ” on top left corner or view “Full screen” icon does not works and I am unable to back to the previous screen even if I press back icon in the browser.

http://learning.creative-edevelopers.com/lp-course/

I would appreciate if you can point out the error and how to resolve it.

Regards

Muhammad IMRAN

**Comment by haihld58** [comment]
Hello Muhammad IMRAN,

Please update Learnpress 2.0.9 and check this issue again. Our developers checked and resolved it in the latest version.
