### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by ahangarha** [LearnPress/learnpress#410]
Hi

I didn't find any information about License of this plugin. would you please add LICENSE.md file in the repo?

**Comment by ahangarha** [comment]
No license? No response? Just close the issue?
Doesn't sound professional.

Am I missing something?

**Comment by tungnxt89** [comment]
Hi ahangarha,

Sorry about that, we miss the task, we'll provide that file soon.

Thanks.

**Comment by ahangarha** [comment]
Oh! That sounds good.
Wish you bests

**Comment by ahangarha** [comment]
Hi @tungnxt89 

Any update? It seems still there is no license in the repo
