### ISSUE TITLE
Quizzes don't have Start button

### ISSUE THREAD

**Issue by gsturgess** [LearnPress/learnpress#412]
I have been running LearnPress on my WordPress website for close to a year and the quizzes have all loaded and worked perfectly.  I keep WordPress and LearnPress up-to-date, as well as other plugins.  However, in the past month, the quizzes show, but there is no button to start the quiz.  So, my candidates can't take any quiz to assess their knowledge.  Even the old quizzes that used to work, don't work anymore.  I have put up the number of Retakes so that I can test that.  I have also tried to manually update the database, but that just froze the whole website and when I aborted and reopened, nothing had changed.
![Screen2](https://user-images.githubusercontent.com/47356862/72082829-77737900-3309-11ea-9063-a2110540e091.jpg)

**Comment by gsturgess** [comment]
I'm really disappointed at the total lack of reaction from LearnPress on this issue.  I can't surely be the only one???

**Comment by gsdmagency** [comment]
There is VERY poor support from them, but maybe this helps you, got it on another forum "I think you already finished the course (**or you passed the course duration**)."

**Comment by gsturgess** [comment]
Hi Gert 

Many thanks for this.  I did finally work out that the student was
attempting to complete quizzes past the course duration.  So I just
changed the duration temporarily. 

Many thanks

---
Gail Sturgess
Agile Leadership Specialist
I help business leaders and managers transition their business to the
New Way of Working 

On 2020-07-01 15:20, Gert Swanepoel wrote:

> There is VERY poor support from them, but maybe this helps you, got it on another forum "I think you already finished the course (OR YOU PASSED THE COURSE DURATION)." 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/LearnPress/learnpress/issues/412#issuecomment-652414033
[2]
