### ISSUE TITLE
Changing Button Text

### ISSUE THREAD

**Issue by findlogan** [LearnPress/learnpress#414]
Is there a way to edit the button text for memberships when viewing a course.

Ex. A membership is added to a user from the levels, and they now have a "Enroll" button instead of a "Begin Course" as desired text.

I am not seeking the default button text, it is the text that the button turns into called "Enroll".

**Comment by francoatmega** [comment]
You can use a theme that support LearnPress, and probabily that functionality will be there, or you can "translate" this button with Loco Translate, I think that LearnPress not support edit of button texts.
Regardless of what method you choose, keep in mind to never alter code directly.

**Comment by timjefferies** [comment]
with css:

button.lp-button.button.button-purchase-course.thim-enroll-course-button {
    word-spacing: -9999px;
    color: transparent;
}
button.lp-button.button.button-purchase-course.thim-enroll-course-button::after {
    content: "PAY NOW";
    visibility: visible;
    word-spacing: normal;
    letter-spacing: normal;
    color: white;
}
