### ISSUE TITLE
Content Drip won't work if localized 

### ISSUE THREAD

**Issue by rslonik** [LearnPress/LearnPress#42]
Example:
Datepicker value in english: 10 Dec 2016
Datepicker value in portuguese: 10 Dez 2016

admin.js checks for NaN in the datepicker value, so "10 Dec 2016" returns false but "10 Dez 2016" returns true.

**Comment by haihld58** [comment]
Hello Rslonik,

Thank you for your report, our developers are working on it.  We will update this issue in the next version of  Content Drip add-on.

**Comment by haihld58** [comment]
Or please mail me at hai@foobla.com. I will send you latest version of the add-on what was resolved localized issue.
