### ISSUE TITLE
Fatal Error on Updating to the latest version

### ISSUE THREAD

**Issue by Zazasco1** [LearnPress/learnpress#421]
I have been using learn press for a long time now, after doing a recent update it caught a fatal error that shuts down my blog, I have to login in with recovery mode to disable. 
since then it refused to activate.
am using WordPress 5.4

**Comment by thimpressweb** [comment]
Hi, We had updated the newest version LearnPress 2.3.6.9 to fix it. Please update to this version, everything will be going well. 
Sorry for your inconvenience.
