### ISSUE TITLE
Garbled English in your description of the plugin

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [LearnPress/learnpress#423]
Here is a description that you provide of your software. 

![image](https://user-images.githubusercontent.com/47056543/80302600-df5bab80-87a2-11ea-96f6-ace493524aef.png)

The text, 'This is one of the best WordPress LMS Plugins can be used to easily [. .]' is garbled. Some of the other sentences need work, too.

It should not need saying, but: as a provider of educational resources, you need to write decently.

**Comment by brianvu-tp** [comment]
Thank you for your advice, we will correct it.
