### ISSUE TITLE
woocommerce payment

### ISSUE THREAD

**Issue by IslamAboAsd** [LearnPress/learnpress#424]
@minhlucvan 
 issue with woocommerce payment addon it stops the website when I use learnprees from wp store its work

**Comment by wilsonrg** [comment]
> Problema @minhlucvan
> com o addon de pagamento do woocommerce para o site quando eu uso o learnprees da wp store

Precisa do plugin learnpress-woo-payment
procure por: LearnPress - WooCommerce Payment Methods Integration

**Comment by eslam200788** [comment]
> > Problema @minhlucvan
> > com o addon de pagamento do woocommerce para o site quando eu uso o learnprees da wp store
> 
> Precisa do plugin learnpress-woo-payment
> procure por: LearnPress - WooCommerce Payment Methods Integration

yup I install it but it's stop website after activating it when I try with learnpress plugin from wp store it works fine
