### ISSUE TITLE
undefinded function wp_get_current_user() due to misconfigured hook

### ISSUE THREAD

**Issue by sh1ku** [LearnPress/learnpress#428]
Learnpress on its latest version (3.2.7.2) crashes the admin panel on some Wordpress setups because is calling wp_get_current_user() when it doesn't exist, via the _learn_press_set_user_items hook in file lp-admin-actions.php line 48. 

Changing add_action( 'pre_get_posts', '_learn_press_set_user_items', 10 ); to add_action( 'init', '_learn_press_set_user_items', 10 ); potentially solves it. plugins_loaded might work as well.

This is probably caused by some incompatibility with the theme, or other plugins that might alter loading procedures.

EDIT

In the last update, the error occurs again. They've seem to have commented out the function that caused problems last update, but now there's a new one.

./inc/admin/class-lp-admin.php:59
add_filter('pre_get_posts', [.....] -> add_filter('init', [.....]

**Comment by M0unir** [comment]
Yes. Same issue with latest update. 

Here is a stack trace:

`Fatal error: Uncaught Error: Call to undefined function wp_get_current_user() in /www/wordpress/wp-includes/capabilities.php:660 Stack trace: #0 /www/wordpress/wp-content/plugins/learnpress/inc/admin/lp-admin-actions.php(19): current_user_can('manage_options') #1 /www/wordpress/wp-includes/class-wp-hook.php(287): _learn_press_set_user_items(Object(WP_Query)) #2 /www/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 /www/wordpress/wp-includes/plugin.php(544): WP_Hook->do_action(Array) #4 /www/wordpress/wp-includes/class-wp-query.php(1768): do_action_ref_array('pre_get_posts', Array) #5 /www/wordpress/wp-includes/class-wp-query.php(3432): WP_Query->get_posts() #6 /www/wordpress/wp-includes/post.php(2050): WP_Query->query(Array) #7 /www/wordpress/wp-content/plugins/modern-events-calendar-lite/app/features/updateTable.php(45): get_posts(Arra in /www/wordpress/wp-includes/capabilities.php on line 660`

**Comment by sh1ku** [comment]
Seems solved, I'll reopen if it happens again.
