### ISSUE TITLE
Lesson list(course content) is shown instead of lesson content

### ISSUE THREAD

**Issue by acitil** [LearnPress/LearnPress#43]
Hello,
I liked the plugin very much. It's amazing. Just I couldn't solve a problem.

When a user takes a course then the course content, lessons are listed.
After clicking a lesson in the list the page show the lesson list in the left frame and then in the right frame it shows the course content again. Then if you click again a lesson in the right frame it opens inside the same frame a new course content and so on.. The page doesnt show the selected lesson. 

the url contains:  mysite.com/lp-courses/category/coursename/lessons/lessonname
if I change this url to: mysite.com/lessons/lessonname it shows the lesson.

What should I do?
Thanks in advance.

**Comment by haihld58** [comment]
Hello acitil,

It's workflow of our plugin. Lesson was included in a course, when you enroll course and click a lesson in this course, It open lesson content in course, not single lesson page.

**Comment by acitil** [comment]
Hi,
Yes I know how it should be. But there is somethin wrong in my site, theme
or plugin and it never shows me the lesson. It always lists the course
content in the right frame too.

28 Ara 2016 03:04 tarihinde "Lee" <notifications@github.com> yazdı:
