### ISSUE TITLE
When a normal user clicks enroll , they get redirected to wordpress login

### ISSUE THREAD

**Issue by yikes13135434** [LearnPress/learnpress#434]
![Captu1e](https://user-images.githubusercontent.com/67499892/85918044-647d4280-b870-11ea-91fa-3a1d0971def6.PNG)
![Capture](https://user-images.githubusercontent.com/67499892/85918046-68a96000-b870-11ea-9592-88ad493ddd74.PNG)

you'll notice that the wordpress login is a redirect. i tried redirecting it , but it didnt work

im looking forward help from learn press

url: http://lucid4tech.com

thank you

**Comment by FernandoC1217** [comment]
Hello, I was with the same problems as you. How was it going? A solution that worked for me was to activate a setting under **WordPress > LearnPress > Settings > Profile** also needed to be ticked (‘Enable register from profile if the user is not logged in.’)

Here is an image 



![imagen](https://user-images.githubusercontent.com/50190625/86797262-17019200-c035-11ea-98e3-ae571e45ca69.png)


Tell me if it worked for you too.
