### ISSUE TITLE
"Ordered" courses statistics not working

### ISSUE THREAD

**Issue by zelimir83** [LearnPress/learnpress#436]
When viewing the statistics from the backend, in the "Ordered" courses tab nothing is shown, and console displays the following errors:

select2.min.js?ver=3.2.7.2:1 Uncaught Error: No select2/compat/inputData

The select2.min.js is a file from learnpress/inc/libraries/meta-box/js/select2/select2.min.js?ver=3.2.7.2

After about 10 seconds additional error gets displayed:

wp-auth-check.min.js?ver=5.4.2:2 Uncaught TypeError: Cannot read property 'hasClass' of undefined

LearnPress version 3.2.7.2, WordPress version 5.4.2
I've deactivated all other plugins and reverted the theme to TwentyTwenty, and the error is persistant.

![image](https://user-images.githubusercontent.com/1748832/87279273-56255c80-c4e7-11ea-8c4a-c23f820fa768.png)

**Comment by MawiaHL** [comment]
I also have the same issue. I hope they fix the issue in Learnpress version 4. Looking at the console, the problem seems to be learnpress usage of the select2 library.
