### ISSUE TITLE
how to edit BUY THIS COURSE button on single course page?

### ISSUE THREAD

**Issue by harshal-sathe** [LearnPress/LearnPress#44]
I want to edit the BUY THIS COURSE button and change the lable to  'Register for this course'. I am new in wordpress . please guide me how I can get this done

**Comment by haihld58** [comment]
Hello Harshal-sathe,

If you want to override template in our plugin, you need create folder learnpress on your theme, copy code in template file you want to change and modify as what you want.

In this case, please create folder learnpress/single-course/ , copy file buttons.php in the plugin and override it in your the path on your theme.

**Comment by francoatmega** [comment]
Indeed its better use Loco Translate instead of change the button content in code. It's very easy to add a translation with Loco Translate

**Comment by codermousumi** [comment]
its not working can you help me
