### ISSUE TITLE
Courses Not Showing Up - 404 Error

### ISSUE THREAD

**Issue by RonCharest** [LearnPress/learnpress#448]
I've created my courses and the course titles along with feature image show up on the Course page. However, when I click on the course title/image, I receive a "404 Page Not Found" error. This occurs even with the sample courses. I would appreciate assistance on resolving this.

Course page

http://edit611.charestconsulting.com/courses-2/

**Comment by Mdhesari** [comment]
I think you are using tutor LMS and it has nothing to do with learnpress!

If I'm wrong please provide more information on that

**Comment by RonCharest** [comment]
Hi Mdhesari,

I decided to go with Tutor LMS, as that works well. Based on a few other issues I had with other plugins, that went away when I changed themes, I suspect that the issue I was having related to the theme I had.

Thanks,
Ron
