### ISSUE TITLE
Cannot assign Quiz to Course

### ISSUE THREAD

**Issue by MarekKriz** [LearnPress/LearnPress#45]
Hello, I have troubles with assigning Quizes to Course. It's working very strange.

Maybe I'm doing something wrong but I really don't know what to do.

How I do it:
1. I create a Quiz with a Questions
2. Then I what to assign it to Course
3. I cannot find my Quiz :-/

Video: http://d.pr/v/JKN0

Can you help me?

PS: We have deadline untill this week with a website and we cannot make it work :-/ If you can help us ASAP I would really appreciate it.

**Comment by haihld58** [comment]
Hello MarekKriz,

I'm sorry because of the late response. Please update Learnpress to latest version 2.0.9 and check this issue again. Please note that: A quiz is just used for only one course.
