### ISSUE TITLE
Google reCaptcha is ignored on LearnPress user registration page.

### ISSUE THREAD

**Issue by Archie22is** [LearnPress/learnpress#450]
Hello @LearnPress team. 

Using your plugin in conjunction with Advanced noCaptcha & invisible Captcha (v2 & v3) displays the ReCaptcha fields but the registration still goes right through even without checking the reCaptcha allowing spam registrations to go through still. 

Let me know if you need anything else with regards to this issue.

**Comment by geandertal** [comment]
@Archie22is, caso seu problema seja resolvido, por favor entre em contato comigo.

**Comment by Marinski** [comment]
I'm experiencing the same issue.

**Comment by tungnxt89** [comment]
Hi @all,

We will check and fixed it on the nex version.

**Comment by vincenzo** [comment]
None of the existing plugins to add a captcha to login and registration seem to affect the login/registration forms in LearnPress. I also don't seem to find a plugin that does that specifically for LearnPress. I am getting a barrage of spam users in my newly launched site. Any help?
