### ISSUE TITLE
Regression in 3.2.8 - Reset a course for a user failing due to Vue not available

### ISSUE THREAD

**Issue by jasonbernstein** [LearnPress/learnpress#453]
In 3.2.8, when loading /wp-admin/admin.php?page=learn-press-tools&tab=course, and error appears in the Javascript console

`Uncaught ReferenceError: Vue is not defined
    at admin.php?page=learn-press-tools&tab=course:803
Uncaught ReferenceError: Vue is not defined
    at admin.php?page=learn-press-tools&tab=course:941
Uncaught ReferenceError: Vue is not defined
    at admin.php?page=learn-press-tools&tab=course:1067`

At the same time, as a result, underneath the fields for resetting a user's status for a lesson our course, you see the tag `{{message}}` which shouldn't be there. Entering a value for the user and lesson and pressing the submit button does not work (it does not popup the Javascript confirmation dialog nor perform the action). 

It appears as if Javascript files needed for Vue are no longer included as part of the webpack distribution.

**Comment by tungnxt89** [comment]
Hi,

We fixed that issues, you can download again LP 3.2.8, then check and reply to us.

Thanks.

**Comment by saeidnr** [comment]
this is still a problem in 3.2.8.2
