### ISSUE TITLE
'rememberme' should be 'remember'

### ISSUE THREAD

**Issue by rbijkercom** [LearnPress/learnpress#455]
https://github.com/LearnPress/learnpress/blob/426e67cf7b1aa03acf63b1da1cec2b85c81a9522/inc/class-lp-forms-handler.php#L98

When ticking the "remember me" box at logging in it doesn't seem to work. The login will still be based on the session. 
But when I change:
'rememberme'    => LP_Request::get_string( 'rememberme' )
to
'remember'    => LP_Request::get_string( 'rememberme' )
it does work.

**Comment by daonham** [comment]
Thank for issues.
We updated in learnpress 4.0.0
