### ISSUE TITLE
Certificates cannot be customized 

### ISSUE THREAD

**Issue by mhr996** [LearnPress/learnpress#457]
When I try to create a new certificate, I don't see the editor or anything, all I see is "Publish the certificate before editing"even though it's published! I've tried everything!
![Cappture](https://user-images.githubusercontent.com/69459856/99522651-95d0e900-299e-11eb-9fc4-7e5cddc2ad4d.JPG)

**Comment by daonham** [comment]
@zacker101 Please update new LearnPress 3.2.8.1 and LearnPress Certificate 3.1.8 version.

**Comment by TheRialD** [comment]
not working, i have the same issue here 
![Captura de pantalla 2020-11-28 005658](https://user-images.githubusercontent.com/74837471/100517915-03360400-316d-11eb-9266-c1c2009dcf1f.png)

**Comment by d0null** [comment]
Same problem, Any news about this.

**Comment by TheRialD** [comment]
> Same problem, Any news about this.

hello, solved in the forum https://thimpress.com/forums/forum/plugins/learnpress-plugin/

i think the plugin is good, but has a LOT of bugs, a LOT, believeme
