### ISSUE TITLE
Can't sort the courses by their price

### ISSUE THREAD

**Issue by cagrioz** [LearnPress/learnpress#459]
Hello,

I tried the following queries:
?post_types=lp_course&order_by=lp_price
?post_types=lp_course&order_by=course_price
?post_types=lp_course&order_by=price

But couldn't sort the courses depending upon their price. Is it possible? How can I do that?

Thank you!

**Comment by daonham** [comment]
Hi @cagrioz 
we are doing sorting function, it will be launched soon. Also, try learnpress version 4 here: https://wordpress.org/support/topic/learnpress-4-0-beta-is-now-available-for-testing/'re coming soon and leave your review.
