### ISSUE TITLE
Fatal error when saving new order

### ISSUE THREAD

**Issue by nicope** [LearnPress/learnpress#465]
I'm getting this error whenever I want to save a new order as completed: 

Message Uncaught Error: Call to a member function get_item_id() on string in /home/huertinu/public_html/wp-content/plugins/learnpress/inc/emails/types/class-lp-email-type-enrolled-course.php:81 

Stack trace: 
#0 /home/huertinu/public_html/wp-content/plugins/learnpress/inc/emails/class-lp-email-enrolled-course-user.php(52): LP_Email_Type_Enrolled_Course->get_object() 
#1 /home/huertinu/public_html/wp-content/plugins/learnpress/inc/emails/types/class-lp-email-type-enrolled-course.php(168): LP_Email_Enrolled_Course_User->trigger('23000', 84, '23000') 
#2 /home/huertinu/public_html/wp-includes/class-wp-hook.php(287): LP_Email_Type_Enrolled_Course->auto_enroll_trigger(23950, 'pending') 
#3 /home/huertinu/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) 
#4 /home/huertinu/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) 
#5 /home/huertinu/public_html/wp-content/plugins/learnpress/inc/order/class-lp-order.php(1226): do_action('learn-press/ord...', 23950, 'pending') 
#6 /home/huer
File /home/huertinu/public_html/wp-content/plugins/learnpress/inc/emails/types/class-lp-email-type-enrolled-course.php

I'm running learnpress 3.0.5 on Woo 4.8.0

Any ideas on what's happening?

**Comment by nicope** [comment]
The order is being created correctly and saved as completed, the user can see the course listed under purchased courses, but it's inscription is not being made correctly (so they can't access the course). Hope this helps.

**Comment by daonham** [comment]
Hello.
Please update LearnPress lastest version and check again.
Thanks

**Comment by nicope** [comment]
deonham, hi!

Thanks for your message. I mistook the version in the initial report, I was running the latest version. 

I reinstalled it and it's now working ok.
