### ISSUE TITLE
Update queries so they can be indexed for faster performance

### ISSUE THREAD

**Issue by jasonbernstein** [LearnPress/learnpress#467]
Our site has not been scaling well so we've been trying to optimize everywhere we can for performance. We found a query that with a minor change can be optimized for indexing. Specifically:
class-lp-user-curd.php function get_orders
change:
`meta_value = %d 
`to:
`meta_value = %s`
because the meta_value field is a string field and not numeric.

On our server it reduced the query time from about .30 seconds to .07 seconds because it could use an index we have on the meta_value field. Minor, but they add up.

**Comment by daonham** [comment]
Hello.
Because _user_id is numberic in table learnpress_order_itemmeta. So when when call with meta_value = %s will slow.
Thanks

**Comment by jasonbernstein** [comment]
@daonham - thanks for responding. 

I disagree, however. The learnpress_order_itemmeta meta_value field is a longtext, not a numeric field. The data in it is numeric, but the field itself is a longtext. You cannot create a numeric index on the field, and if you run an EXPLAIN query using a numeric field when you have a text(50) index created, you will get a warning such as:

> Warning: #1739 Cannot use ref access on index 'myindex' due to type or collation conversion on field 'meta_value'`

This doesn't happen if the query uses `%s` and the query performance massively improves.

If you are only storing integers in meta_value - it is an odd choice for a data type. Ideally, you would have a clean upgrade path to change it to a numeric type to speed it up, but in the meantime, please treat it as a string, since it is.

There are other instances where a query against meta_value (in learnpress tables and postmeta and usermeta as well) uses `%d` instead of `%s` and I see similar performance improvements when there is a text index created. Here are some:

**count_by_orders** function in class-lp-course-curd.php (This chopped about 0.5 seconds off of the query time on my server.)
```
$in_courses_clause = join( ',', array_fill( 0, sizeof( $fetch_ids ), '%d' ) );`
```

**read_orders** in class-lp-user-curd.php 
```
$sql_orders = $wpdb->prepare( "
                                SELECT ID, post_title, post_name, post_status, post_type, post_parent, post_date
                                FROM {$wpdb->posts} p
                                INNER JOIN {$wpdb->postmeta} pm ON p.ID = pm.post_id AND meta_key = %s AND meta_value = %d
                        ", '_user_id', $user_id );
```

**get_current_user_order** in class-lp-user-curd.php (twice): 
```
                $sql      = $wpdb->prepare( "
                        SELECT MAX(ID) AS order_id
                        FROM {$wpdb->posts} p
                        INNER JOIN {$wpdb->postmeta} pm_u ON pm_u.post_id = p.ID AND pm_u.meta_key = %s AND pm_u.meta_value = %d
                        INNER JOIN {$wpdb->learnpress_order_items} oi ON oi.order_id = p.id
                        INNER JOIN {$wpdb->learnpress_order_itemmeta} oim ON oim.meta_key = %s and oim.meta_value = %d
                ", '_user_id', $user_id, '_course_id', $course_id );
```

**update_course** in class-lp-email-updated-course.php
```
$query = $wpdb->prepare( "
                                SELECT pmt.meta_value
                                FROM {$wpdb->posts} o
                                INNER JOIN {$wpdb->learnpress_order_items} oi ON oi.order_id = o.ID
                                INNER JOIN {$wpdb->learnpress_order_itemmeta} oim ON oim.learnpress_order_item_id = oi.order_item_id
                                INNER JOIN {$wpdb->prefix}postmeta pmt ON pmt.meta_key = %s and pmt.post_id = oi.order_id
                                AND oim.meta_key = %s AND oim.meta_value = %d
                                WHERE o.post_status = %s
                        ", '_user_id', '_course_id', $post_id, 'lp-completed' );
```

**posts_where_paged** in inc/custom-post-types/order.php
```
$sql       = " ( pm1.meta_value = %d OR pm1.meta_value LIKE %s)";

```

**_create_pages** in inc/class-lp-install.php
```
                                                                $page_id = $wpdb->get_var(
                                                                        $wpdb->prepare( "
                                                                        SELECT ID
                                                                                FROM $wpdb->posts p
                                                                                INNER JOIN $wpdb->postmeta pm ON p.ID = pm.post_id AND pm.meta_key = %s AND pm.meta_value = %d
                                                                ", '_lpr_is_profile_page', 1 )
                                                                );

```

**schedule_cleanup_temp_users** in inc/user/class-lp-user-factory.php (comparing a timestamp numeric to a string field with no conversion. Make sure this works as expected - CAST something, but check performance)
```
                $query = $wpdb->prepare( "
                        SELECT user_id
                        FROM {$wpdb->prefix}learnpress_user_items c
                        INNER JOIN {$wpdb->prefix}learnpress_user_itemmeta d ON c.user_item_id = d.learnpress_user_item_id AND d.meta_key = %s
                        INNER JOIN {$wpdb->prefix}learnpress_user_itemmeta e ON c.user_item_id = e.learnpress_user_item_id AND e.meta_key = %s AND e.meta_value < TIMESTAMPADD(SECOND, %d, NOW())
                ", 'temp_user_id', 'temp_user_time', self::$_guest_transient );
```

I also see a few instances in the learnpress-paid-membership-pro and learnpress-co-instructor plugins (unscientifically by grepping for meta_value and %s)
