### ISSUE TITLE
Error: Params invalid 

### ISSUE THREAD

**Issue by Argos99** [LearnPress/learnpress#468]
When adding the course to cart we get the error: Params Invalid. It doesn't always happen in my browser, but it does on mobile devices. Some people don't have any issues, others do.

Can someone please help? 
![IMG_4874](https://user-images.githubusercontent.com/79800231/109424605-8cffa280-79e4-11eb-8420-17f525e636d6.jpg)

**Comment by amir-danesh** [comment]
I have the exact same problem. did you find any solutions?

**Comment by Argos99** [comment]
Beste,

dank voor je mail! In verband met vakantie zijn wij gesloten. Vanaf 24 augustus zullen we je mail beantwoorden.

Vriendelijke groet,

Miriam Eijgenstein
Kenniscentrum Argos - Argos Scentwork Academy
