### ISSUE TITLE
archive-course.php template can't be overriden in the theme folder?

### ISSUE THREAD

**Issue by Mofect** [LearnPress/learnpress#470]
Hi

I use LearnPress 4.0.1, the new version completely changed the original website pages, so I want to custom archive-course.php, single-course.php templates, but after I copied them to themefolder / learnpress, it seems they can't be overridden?

I'm sure the folder and file name is correct.

Any suggestions?

Thanks

**Comment by yash19070** [comment]
hello 
page override is not working in v.4 
please any one have solution provide us 
our production is stopped due to this problem 
thank you

**Comment by daonham** [comment]
Hello.
You can use filter: `add_filter( 'learn-press/override-templates', function{ return true; } );` to function.php in your theme.
Thanks

**Comment by rasel-xs** [comment]
Using this filter, the archive page is working properly but the single page is not working. What can I do to solve this? We have 3000+ customers and this is an urgent issue. Please provide a quick response. 

Thank you

**Comment by tahminaxspeed** [comment]
Hello,
After updating the Latest version of LearnPress a lot of issues are facing. From the template folder few files has been removed (profile/proile.php, profile/profile-cover.php) etc files. Please give us a proper documentation where we can find which files are removed and moved the code/functionality to other files. As it is an urgent issue, we need a guideline to understanding everything. Please give a solution. :)

**Comment by alexposlushnyak** [comment]
+1 Same problem. Please fix this asap. 'learn-press/override-templates' filter doesn't completely solve the problem.

**Comment by trangnb** [comment]
Hey everyone, all the detail change of LearnPress 4 in [here](https://docspress.thimpress.com/developer-learnpress/)

**Comment by rasel-xs** [comment]
HI,
profile page doesn't work after updating. We have override leanrpress template. Please guide me what can I do

Thanks

**Comment by daonham** [comment]
Hi @rasel-xs 
Please go to LearnPress > Settings and set Profile page.
Thanks
