### ISSUE TITLE
LearnPress Version 4.0.1  - Auto enroll

### ISSUE THREAD

**Issue by gee123123** [LearnPress/learnpress#471]
Hope anyone can help . I have some chaos after the update to Version 4.0.1.

1) Previously it was set up that new user got auto enrolled. Now I am missing that option and have this "start now" button everywhere to enroll

![auto enroll](https://user-images.githubusercontent.com/84034812/117870884-01847680-b29d-11eb-88fc-910b763272ad.png)

Can anyone point me in the right direction? Where can I hide this or shut it off? 

Thanks a lot in advance

**Comment by daonham** [comment]
Hello.
You can go to LearnPress > Settings > Course.
You can enable "Auto Start" button.
Thanks

**Comment by gee123123** [comment]
Thanks @daonham, however this banner to enroll is still there which causes now confusion for my members. Anyhow I guees this is just nothing we can change now. Thanks anyway
