### ISSUE TITLE
color in heading - learnpress Version 4.0.1

### ISSUE THREAD

**Issue by gee123123** [LearnPress/learnpress#472]
Hi,

1)
can anyone tell where or if  I can change the color 

![learn press](https://user-images.githubusercontent.com/84034812/117860008-10186100-b290-11eb-8b92-b7ad3a674f6d.png)

2) My content is free.  In order to make it availabe I had to set the preview option on the lessons. 
Is there a possibility that "preview" is not displayes everywhere?

thank you

**Comment by daonham** [comment]
Hello.
1. You can go to LearnPress > Settings > Advanced and you can change for color.
2. Currently we only have the Preview in Lesson option, the Preview for Course option we will consider adding if more guests need it.

Thanks
