### ISSUE TITLE
How to remove an action that uses 'callback' and 'text' in LearnPress 4.x

### ISSUE THREAD

**Issue by ibndawood** [LearnPress/learnpress#473]
Hello there,

How do I remove the following actions in my child theme?

```
add_action(
	'learn-press/course-content-summary',
	LP()->template( 'course' )->text(
		'<div class="course-detail-info"> <div class="lp-content-area"> <div class="course-info-left">',
		'course-info-left-open'
	),
	10
);
add_action(
	'learn-press/course-content-summary',
	LP()->template( 'course' )->callback( 'single-course/meta-primary' ),
	10
);
```

Thanks,
Ibrahim

**Comment by daonham** [comment]
Hello.
You can use code for  remove action:

`LP()->template( 'course' )->remove( 'learn-press/course-content-summary', array( '<div class="course-detail-info"> <div class="lp-content-area"> <div class="course-info-left">',
'course-info-left-open' ),
	10
);

LP()->template( 'course' )->remove_callback( 'learn-press/course-content-summary', 'single-course/meta-primary', 10 );`

Thanks

**Comment by ibndawood** [comment]
Brilliant. I understand that this could be a tough time for you with a lot of websites breaking due to the 4.x update. I appreciate your help.
