### ISSUE TITLE
LP4 require version Thim-core: 2.0.0-beta-0

### ISSUE THREAD

**Issue by vincemadai** [LearnPress/learnpress#474]
My _working_ Coaching WP site broke down in the last days, all Thimcore widgets are gone. 
Checking the page I can see that it asks me to re-active Thimcore.
When I try to do that, I get this error: "LP4 require version Thim-core: 2.0.0-beta-0" 

However, there is no option or trigger to upgrade the Thimcore plugin-version (currently 1.10.2) to any version 2.x. 

Any ideas?

**Comment by daonham** [comment]
Hello.
Please update Coaching latest version, then you can update Thim-core 2.0.0.
Thanks

**Comment by vincemadai** [comment]
Hi, 
thanks for your answer. 
My Coaching version is 3.3.3 and there is no prompt to update the theme. I checked this first.
I see now another message, however, that some LP files are outdated and I "may need to update". 
So it seems you are right.
But: as I said, there is no update available...

How to proceed?

**Comment by daonham** [comment]
Hi @vincemadai 
You can deactive and delete Thim-core, 
Then wordpress will notice install Thim-core, you install Thim-core again.
It will install Thim-core latest version for you.
Thanks

**Comment by vincemadai** [comment]
That solved it! 
Thank you so much. Your help is much appreciated! :-)
