### ISSUE TITLE
LearnPress version 4.0.3 require learnpress-paid-membership-pro version 4.0.0-beta-0 or higher

### ISSUE THREAD

**Issue by Likhithlpu** [LearnPress/learnpress#475]
While activating the plugin i am getting this error. May i know why i am getting this and this error too
**LearnPress Stripe Payment addon version 1.1.0 requires LearnPress version 3.1.0 or higher is installed and activated.**

**Comment by Likhithlpu** [comment]
I am also getting this popuptoo 
**LearnPress Paid Memberships Pro addon version 3.1.8 requires LearnPress version 3.0.0 or higher is installed and activated.**

**Comment by daonham** [comment]
Hello. 
Please update LearnPress Paid Membership latest version.
Thanks
