### ISSUE TITLE
After updating to version 4.0 nothing is working. Lèssons and quizzes remain locked after purchasing or even for a course that is gratis. Is it due to the wp education theme I am using? Do I need to buy a pro version of the theme or better a pro version of LP plug in or both?

### ISSUE THREAD

**Issue by Danilaus79** [LearnPress/learnpress#480]
Any suggestion? Thank in advance

**Comment by daonham** [comment]
Hello.
Are you update database in LP4?
After update to LP4, you need update database to version 4.
You can go to LearnPress > Tools.
Thanks

**Comment by Danilaus79** [comment]
Already done but the issue is still there. I am thinking that maybe is due to the theme? I am using a free theme called "Education WordPress theme"

**Comment by Danilaus79** [comment]
Which is the best working theme ti ne used for LP4?

**Comment by bjorne51** [comment]
I have the same problem,  when clicking on a course to buy (even if it is free) you just get rediceted to an empty cashout

 page. THis happend after the last update and the DB is also updated. Customers that already bought a course, cannot log n again!
I am losing money every day, please fix this big bug!

![2021-05-29](https://user-images.githubusercontent.com/85014794/120065297-da85bd00-c070-11eb-9eba-897cdc3fbf98.png)

**Comment by Danilaus79** [comment]
Maybe I inderstand the issue, it is the external link that is not working anymore...since i am using woocommerce, the only way to have LP working well is to remove the external link ti woocommerce

**Comment by bjorne51** [comment]
I tried to deactivate woocommerce, but is doenst help. I use paypal only. But still making a new order does end up on an empry chart site. Where is the support?

**Comment by Danilaus79** [comment]
I am afraid that since LP is free, no way to solve this issue unless you pay to upgrade LP. If it is this the case, I prefer to move directly to Learn Dash

**Comment by Marinski** [comment]
> I am afraid that since LP is free, no way to solve this issue unless you pay to upgrade LP. If it is this the case, I prefer to move directly to Learn Dash

Why don't you make backups before you make an update? You should always back up your site, even when there is a small plugin or theme change. Anyway, I assume you didn't make a backup of your site, in this case, you can try to contact your hosting provider and ask them about the date of the most recent cPanel backup, and if it's not too old, ask them to recover it. Depending on your knowledge and infrastructure, if you have a backup of your database on the server, then you can manually replace the files of your WP site.
