### ISSUE TITLE
paganation

### ISSUE THREAD

**Issue by yash19070** [LearnPress/learnpress#481]
hello 
when i login in lp-profile of the user and go to load more course in will loading but not working or retrive any course 
![image](https://user-images.githubusercontent.com/37044566/119310896-04646b80-bc8e-11eb-8fed-f6c07ef145bd.png)

**Comment by daonham** [comment]
Hello,
Please enable WP_DEBUG and WP_DEBUG_LOG and check file debug.log in wp-content folder.
Thanks
