### ISSUE TITLE
LearnPress 4.0.2 update problems when I update database

### ISSUE THREAD

**Issue by llllluis** [LearnPress/learnpress#485]
When I started to update LearnPress’database in the first step “Create tables learnpress_user_item_results” appers this error “The response is not a valid JSON”, How Can I resolve?
Thanks

**Comment by tungnxt89** [comment]
Hi llllluis,

We think has some errors before show that step return invalid js.

Please enable WP_DEBUG and WP_DEBUG_LOG and send us file wp-content/debug.log. We'll check that.

Thanks.
