### ISSUE TITLE
PHP session cookies don't play nicely with varnish cache

### ISSUE THREAD

**Issue by vorpalvorpal** [LearnPress/learnpress#486]
The PHP session cookies _wordpress_lp_guest and _learn_press_session_ prevent varnish caches from working. A temporary work around would be to at least provide custom VCL in the docs for users using a varnish cache. Longer term, it would be good to move away from PHP session cookies as these are generally not best practice for wordpress development. The following describes alternatives to PHP sessions: https://kinsta.com/blog/wordpress-cookies-php-sessions/

**Comment by tungnxt89** [comment]
Hi ,

It same topic with Woocommerce on the https://github.com/woocommerce/woocommerce/issues/21944

We think current we don't has solution repleace.

Thanks.
