### ISSUE TITLE
after upgrade to 4.x lessons page is empty

### ISSUE THREAD

**Issue by ittrainingdotpro** [LearnPress/learnpress#490]
after the update to 4.x none of the lessons page load. the page has only html and <head>, the body is empty. none of the curriculum pages load.

**Comment by tungnxt89** [comment]
Hi,

Can you write detail, extactly your issues, or send us some images?

Are you upgrade Database success like on the guide https://docspress.thimpress.com/upgrade-database-how-to-fix-some-issue/

**Comment by u451f** [comment]
Might be that the update partly failed.
