### ISSUE TITLE
Infinite wp-cron spawns of `POST /wp-admin/admin-ajax.php?action=lp_installer`

### ISSUE THREAD

**Issue by jerclarke** [LearnPress/learnpress#498]
I am able to install LP on my local MAMP server just fine, but on our live server enabling the plugin causes a performance issue so profound it crashes our entire 8-core 16gb nginx+php+redis server. After enabling, and even after running the install wizard, the server is barraged with requests to `POST /wp-admin/admin-ajax.php?action=lp_installer`, here's how it looks in the logs:

```
[IP ADDRESS of the web server] - - [08/Oct/2021:23:15:27 +0000] "POST /wp-admin/admin-ajax.php?action=lp_installer&nonce=29b955b84e HTTP/1.1" 499 14 .9si67 0 "https://[SITE]/wp-admin/admin-ajax.php?action=lp_installer&nonce=29b955b84e" "WordPress/5.4.6; [SITE]"
```

This happens over and over, hundreds of requests that eventually DOS the server from the inside. 

I haven't solved it yet, but it seems other have had this issue, as evidenced by this [WPMUDev.com support ticket](https://wpmudev.com/forums/topic/hosting-high-cpu-with-learnpress-plugin/) where a user had a similar result. 

The solution in their case was to flush the object cache after enabling the plugin. This is not a good solution because in the meantime the server will be overwhelmed, and I will need to remember to do this every time I enable the plugin. 

Have you tested LP with object caching plugins? Specifically the [main redis object cache plugin](https://wordpress.org/plugins/redis-cache/)?

Have you come across issues like this before?

## Apparent cause

I found that WPMUDev support ticket because I was searching for `LP_Background_Installer`, the class which creates the `admin-ajax.php?action=lp_installer` requests. 

The WPMUDev support staff seem to think that the problem is the constructor, and that it is somehow failing to check the cache:

```
	public function __construct() {
			parent::__construct();

			if ( 'yes' !== get_option( 'learn_press_check_tables' ) ) {
				$this->push_to_queue( array() )->save()->dispatch();
			}
		}
```

I still need to test this more.

**Comment by tungnxt89** [comment]
Hi jerclarke,

Thanks for your feedback. This function only run if all tables of LP require did not create, we're trying to improve that.

Thanks.
