### ISSUE TITLE
Not able to deregister the font-awesome library 

### ISSUE THREAD

**Issue by jatindv** [LearnPress/learnpress#502]
There was some font-awesome conflict with theme.  
I have deregister the script and issue is resolved (this working fine in LearnPress 4.0).
But in latest version 4.1.4 deregister script is not working it's breaking the LearnPress. css completely

Reason that I found is dependency is added on LearnPress css.
File ::  inc/class-lp-assets.php.
function :: _get_styles
![image](https://user-images.githubusercontent.com/42375000/144373165-6b4f02eb-5bb2-4d3f-85a6-80807f8e6586.png)

Is there any way to deregister or dequeue font-awesome style?

**Comment by tungnxt89** [comment]
Hi jatindv,

Because learnpress dependency font-awesome-5. So if you deregister that, it will be broken some style.

On the future will try not use font-awesome-5.

Thanks.
