### ISSUE TITLE
LearnPress error: Query lp/v1/courses/archive-course learnpress

### ISSUE THREAD

**Issue by AssadMalik** [LearnPress/learnpress#503]
Please fix this issue. LearnPress has an Ajax error conflict with WooCommerce. We are not able to get the payment method that is connected with WooCommerce.

**Comment by tungnxt89** [comment]
Hi AssadMalik,

Can send us some error about that? We checked it, but don't see any error as you talk about.

Thanks.

**Comment by alexlealch** [comment]
Hi, my error don´t let open the courses page. The error say: Error: Query lp/v1/courses/archive-course

**Comment by hatem-mazid** [comment]
Hello

I'm facing th same issue, I'm using learn press with learnPress woocommerce payment methods integration

**Comment by tungnxt89** [comment]
> Hello
> 
> I'm facing th same issue, I'm using learn press with learnPress woocommerce payment methods integration

Can you provide us type Payment of Woo make has errors?

**Comment by UnimartTeam** [comment]
@tungnxt89 Direct bank transfer, but i don't think its related to the payment method

**Comment by hatem-mazid** [comment]
@tungnxt89 Direct Bank Transfer

**Comment by tungnxt89** [comment]
Hi,

This error can be from the plugin Woo. You can read the topic https://wordpress.org/support/topic/error-query-lp-v1-lazy-load-course-curriculum/

Thanks.
