### ISSUE TITLE
Guest User

### ISSUE THREAD

**Issue by P0stman** [LearnPress/learnpress#505]
Hi Expert,

Having some issue with guest users that if item was bought it records as if "Guest User" already bought the item and nobody can buy it further as guest.
Buy button disappears and error that i can see : wp-json/lp/v1/courses/continue-course?_locale=user 401 unauthorized .
{
    "code": "rest_forbidden",
    "message": "Sorry, you are not allowed to do that.",
    "data": {
        "status": 401
    }
}

**Comment by tungnxt89** [comment]
Hi P0stman,
When guest user buy course success, they must login with account bought to learn the course.

Thanks.

**Comment by P0stman** [comment]
Hi @tungnxt89 ,
Indeed ..but the problem is that guest cannot buy the course .
It works for the first time but after the first purchase as guest user there is no more option to buy the course .
this looks like some cache from the plugin.

**Comment by tungnxt89** [comment]
Hi P0stman,

Can you send us the capture video that issues? you can upload to https://www.loom.com/

Thanks.

**Comment by tungnxt89** [comment]
Hi,

We fixed that on the version 4.1.6.2

Thanks.
