### ISSUE TITLE
replacement for can_finish_course missing

### ISSUE THREAD

**Issue by TerrePorter** [LearnPress/learnpress#506]
The replacement function for can_finish_course is not in the LP_User class and I could not find it anywhere in the code.

https://github.com/LearnPress/learnpress/blob/7c738f910ec3ba88257d17a813ce440783e3f5f5/inc/user/abstract-lp-user.php#L1148-L1152

**Comment by tungnxt89** [comment]
Hi TerrePorter,

You can use "can_show_finish_course_btn" function on the "inc/user/class-lp-user.php" replacement that function.

Thanks.
