### ISSUE TITLE
How to generate Certificate ID ?

### ISSUE THREAD

**Issue by rahim3070** [LearnPress/learnpress#507]
Let me know, How can I add an auto generated certificate id in my certificate ?

**Comment by rahim3070** [comment]
>

**Comment by tungnxt89** [comment]
Hi rahim3070,

To do that, you need custom code.

1. You can create new layer class extends from LP_Certificate_Layer
2. Or simply, you can edit class LP_Certificate_Student_Name_Layer and add function uniqid() asssign for $this->options['text'] variable.

Thanks.
