### ISSUE TITLE
Learnpress API list all courses Sections are missing

### ISSUE THREAD

**Issue by brucemckayone** [LearnPress/learnpress#508]
There is a problem with the API calling meaning there the courses sections are not sent with the api call

**Comment by tungnxt89** [comment]
Hi brucemckayone,

Can provide detail your issues? We don't clear.

Thanks.

**Comment by brucemckayone** [comment]
After the previous two updates.  When fetching courses from the Learnpress
API
The course JSON is returned, but the the sections part which has the
sections and lessons an empty list.

I fixed by rolling back twice.

**Comment by tungnxt89** [comment]
Hi brucemckayone,

With the LP v4.1.7.3.2, are the issues fixed?

Thanks.

**Comment by brucemckayone** [comment]
Issue has been fixed

**Comment by tungnxt89** [comment]
Hi brucemckayone,

Thank you for your feedback. Are you try to LP version [4.2.0-beta-1](https://thimpress.com/learnpress-4-2-0-beta-1-now-available/) on the Test site?

On the version, we change and optimize more. If you use it, please feedback for us.

Thanks.
