### ISSUE TITLE
New lessons order changes after updating course page

### ISSUE THREAD

**Issue by kerimsarigul** [LearnPress/learnpress#509]
The newly added lessons to the course are at the bottom of the list.
After updating, the order of the last lessons changes.
LearnPress Version: Sürüm: 4.1.6.2

![order of lessons changes10](https://user-images.githubusercontent.com/54417583/162338011-e668339a-d1de-48ae-84c5-05fa9b78cd41.gif)

**Comment by tungnxt89** [comment]
Hi kerimsarigul,

We will fix on the next version 4.1.6.3

Thanks for feedback.
