### ISSUE TITLE
Alternative function for get_purchased_courses() to get user courses in LearnPress v4.1.6

### ISSUE THREAD

**Issue by rajaeinet** [LearnPress/learnpress#510]
Hi,
Is there a function to get all courses of a specific user in v 4.1.6 and it's onwards?

Prior to version 4.1.6, the `get_purchased_courses()` function defined in path below was used:
- `learnpress/inc/user/abstract-lp-user.php`

But since this function is deprecated by it's editor (@tungnxt89), I couldn't find any replacement!
If there is a way in new versions to replace it, please help me.
thank you! 😄

**Comment by tungnxt89** [comment]
Hi ,

We replied for you on the topic https://github.com/LearnPress/learnpress/issues/511#issuecomment-1126673323

You can try :)

Thanks.
