### ISSUE TITLE
Bug: Undefined method LearnPress::get_user() called!

### ISSUE THREAD

**Issue by rajaeinet** [LearnPress/learnpress#511]
Hi,
As find alternative way to get all user courses (described in #510 ), I wanted to use `learn_press_get_enrolled_courses()` function, but I got a fatal error! (function has been attached.)
`get_user()` method in `LP()->get_user( $user_id )` is not defined.
Tested vesions: 4.1.5 and 4.1.6

**Error**:
Fatal error:  Uncaught Error: Call to undefined method LearnPress::get_user() in WPPath\wp-content\plugins\learnpress\inc\lp-core-functions.php:1004

![2022-04-30_234225](https://user-images.githubusercontent.com/89868505/166119629-e128d08c-39b9-4f34-ba67-34711b03cd86.png)

**Comment by tungnxt89** [comment]
Hi,

This function is deprecated on the version 4.1.6.4

You can use below code:

`
$filter  = new LP_User_Items_Filter();
$filter->user_id = $user_id;
$total_rows     = 0;
$result_courses = LP_User_Item_Course::get_user_courses( $filter, $total_rows );
`

You can read more query on function "get_user_courses" on "inc/databases/class-lp-user-items-db.php"

Thanks.

**Comment by rajaeinet** [comment]
> You can use below code:
> 
> ```
> $filter  = new LP_User_Items_Filter();
> $filter->user_id = $user_id;
> $total_rows     = 0;
> $result_courses = LP_User_Item_Course::get_user_courses( $filter, $total_rows );
> ```
> 
> You can read more query on function "get_user_courses" on "inc/databases/class-lp-user-items-db.php"

Thanks for the tips 😄
