### ISSUE TITLE
Bug: Can't insert items in my courses

### ISSUE THREAD

**Issue by giuliano-gvnn** [LearnPress/learnpress#512]
It is not possible to insert lessons in "curriculim / details" "Create new lesson" works only by refreshing the page and the "select items" button does not work at all.

**Comment by tungnxt89** [comment]
Hi giuliano-gvnn,

Please open dev of browser and see has any errors? We check but don't see error like you.

Thanks.

**Comment by giuliano-gvnn** [comment]
No error appears, as you can see:
https://youtu.be/kaUFA-_k6j4

**Comment by tungnxt89** [comment]
Hi giuliano-gvnn,

What is the version LP you are using? Please send us info site.

Thanks.

**Comment by giuliano-gvnn** [comment]
WP version 6.0
LP version 4.1.6.5
PHP version  7.4.29

Other Plugins

https://pastebin.com/6zHXLZNm

Need some other info?

**Comment by tungnxt89** [comment]
Hi giuliano-gvnn,

We need debug your site, because your is the first person has that issue. Please send us admin info to lewis@thimpress.com. We'll check it.

Thanks.
