### ISSUE TITLE
learn_press_course_curriculum shortcode doesnt load css/js

### ISSUE THREAD

**Issue by buonzz** [LearnPress/learnpress#515]
Hi,

In my homepage, I've placed the following shortcode

```
[learn_press_course_curriculum id="9215"]
```

wherein the 9215 is the course id on which i wanted to show the curriculum (e.g list of sections and lessons).
the problem is the time styling on the left, and the collapse is not working (e.g when you click the section arrow thing, it doesnt expand/collapse)
 in here https://filmthatbuild.com/
<img width="1217" alt="Screen Shot 2022-07-08 at 10 00 25 PM" src="https://user-images.githubusercontent.com/946233/178007075-4d3d7681-061c-4179-b498-4c36d7d3c3cf.png">

I wanted for it to behave like in this page: https://filmthatbuild.com/courses/gusto-kong-mag-wood-working/
<img width="877" alt="Screen Shot 2022-07-08 at 10 02 12 PM" src="https://user-images.githubusercontent.com/946233/178007305-bbebbdb3-d1eb-4e5d-8e4b-e929d4511b32.png">

did anyone happen to know what i did wrong with using the learn_press_course_curriculum shortcode?

**Comment by tungnxt89** [comment]
Hi buonzz,
We go to the site https://filmthatbuild.com/, and see the style display normally. If you use theme Eduma and have errors you can create topic on the https://thimpress.com/ , we'll check for you.

Thanks.
