### ISSUE TITLE
Gradebook Error

### ISSUE THREAD

**Issue by agusgonzalezs** [LearnPress/learnpress#517]
Hello, I have the gradebook plugin, it only shows 6 results of enrolled students and no more. How can I solve it? Looks like a plugin bug.

**Comment by tungnxt89** [comment]
Hi agusgonzalezs,

What is the version gradebook addon you use?

You use the premium plugin, so you can create a topic on the [Thimpress forum](https://thimpress.com/forums/forum/learnpress-premium-add-ons/?v=62e491509c757)

We'll check that.

Thanks.
