### ISSUE TITLE
Problem in displaying Section Title on v4.1.6.9.1

### ISSUE THREAD

**Issue by rajaeinet** [LearnPress/learnpress#519]
Hi @tungnxt89 ,
I just updated to LearnPress v4.1.6.9.1,
Now all section names are shown in illegible structure! (Like image below:)
![Illegible on v4 1 6 9 1](https://user-images.githubusercontent.com/89868505/183094637-75d0f72f-30ad-4bfb-8999-ae12d6d9499f.png)

There's no conflict with other plugins because I also tested it on pure wordpress without any other plugins.

It seems likely problem come from where we retrieve section title in `loop-section.php` line 46.

Other details:
- Language: Persian (fa_IR)
- DB Collation: `utf8mb4_general_ci` (and I tested it with `utf8_general_ci` also)

**The correct display**:
On v4.1.6.8 the Section title and it's id are shown like below: (id is Persian Characters in Unicode mode)
![OK on v4 1 6 8](https://user-images.githubusercontent.com/89868505/183094984-0b94993c-992c-4428-b7e0-537973071fb7.png)

Thanks for your attention. :)

**Comment by rajaeinet** [comment]
I found a closer reason for this problem:
**This title is illegible when retrieved from DB.**

I checked the Post meta Content and noticed all `_lp_info_extra_fast_query` meta keys contain illegible section title!
So, when we retrieve that in `get_info_extra_for_fast_query()` function in `inc/course/class-lp-course.php` line 312, the data shown incorrect.

Probably when we save the meta, data is incorrect. (`set_info_extra_for_fast_query()` function and anywhere we call it)

**Comment by rajaeinet** [comment]
Hi there again!
I fixed this issue in #520 Pull Request by adapting `json_encode()` with Unicode data.

**Comment by tungnxt89** [comment]
Hi,

Thank you so much, we reply to you on the [link](https://github.com/LearnPress/learnpress/pull/520#issuecomment-1207596416)

**Comment by rinart73** [comment]
I faced the same issue. It seems that it happens because Wordpress `update_post_meta` uses `update_metadata` which uses `wp_unslash`. Another solution would be to escapes slashes after `json_encode` using https://developer.wordpress.org/reference/functions/wp_slash/

**Comment by tungnxt89** [comment]
Hi all,

We updated LP v4.1.6.9.2 to fix that issue.

Thank all.
