### ISSUE TITLE
where is the full screen option

### ISSUE THREAD

**Issue by rouxito** [LearnPress/learnpress#521]

**Comment by rouxito** [comment]
Hello,
when I'm in the course page, I have a cross on the top right of the screen showing to close up the course.

![Capturan 223 01 55](https://user-images.githubusercontent.com/110745529/183267208-e00ab701-6f4c-4bf7-a8df-a065b554b45a.png)


But the full screen button doesn't showing...(??)
Look like this :

![Capture d’écra3 20 12](https://user-images.githubusercontent.com/110745529/183267196-2b136679-3a25-4178-b172-bff94220345b.png)

Is there a way to reveal this option on the top right of the screen ?
Thank you :)

**Comment by tungnxt89** [comment]
Hi,

You can add code `<input type="checkbox" id="sidebar-toggle" />` to where you want to display on the single item.

Thanks.

**Comment by rouxito** [comment]
You are a genius ! thanks a lot :)
