### ISSUE TITLE
v4.1.6.9.3 popup sidebar not showing in mobile

### ISSUE THREAD

**Issue by buonzz** [LearnPress/learnpress#523]
when in mobile, the menu on the right side is not displaying  because of this css rule

```
@media screen and (max-width: 782px)
#popup-course #sidebar-toggle:checked ~ #popup-sidebar {
    flex-basis: 0;
}
```

demo: https://user-images.githubusercontent.com/946233/184900691-9d01a0a6-564f-4681-a073-ad9d71100071.mp4

**Comment by tungnxt89** [comment]
Hi buonzz,

Thanks for the feedback, we'll check and fix it :) .
