### ISSUE TITLE
can't activate plugin with Wordpress 6.1

### ISSUE THREAD

**Issue by apollo564** [LearnPress/learnpress#529]
It seems that this plugin does not work with the latest Wordpress version (6.1). I'm unable to activate the plugin.

**Comment by tungnxt89** [comment]
Hi apollo564,

The plugin is compatible with WP 6.1. Can you send us some images of the errors?

Thanks.

**Comment by Aiosa** [comment]
Can confirm, with  v`4.1.6.8`, installing WP 6.1 totally broke down the system, both visually and functionally. Since [4.1.4.1-beta-1](https://github.com/LearnPress/learnpress/releases/tag/4.1.4.1-beta-1) is the newest in releases, I can't imagine how it is compatible.

**Comment by tungnxt89** [comment]
Hi Aiosa,

Currently, LP is released v4.1.7.3.2. The next week, we will release [LP v4.2.0](https://downloads.wordpress.org/plugin/learnpress.4.2.0.zip).

You should try it, and when having any errors, please feedback to us.

Thank you so much.
