### ISSUE TITLE
Learnpress 4.2.0 Broke Addon Templates being loaded from Themes and Child Themes

### ISSUE THREAD

**Issue by Polybear-Philippe** [LearnPress/learnpress#532]
The updates to get_template in inc/abstracts/abstract-addon.php disallowed template loading from Child Themes.   This is the function:

```
	public function get_template( string $template_name = '', $args = [] ) {
		$default_path        = $this->plugin_folder_path . "/templates/$template_name";
		$folder_name_rewrite = learn_press_template_path();
		$from_theme_path     = sprintf(
			'%s/%s/%s/%s/%s',
			get_template_directory(),
			$folder_name_rewrite,
			'addons',
			str_replace( 'learnpress-', '', $this->plugin_folder_name ),
			$template_name
		);
		$path_load           = file_exists( $from_theme_path ) ? $from_theme_path : $default_path;
		Template::instance()->get_template( $path_load, $args );
	}
```

There are a few problems here:

- get_template_directory() only returns the Theme not a child theme so you cannot put the template in the child theme
- file_exists call doesn't really work as the template_name doesn't have a ".php" suffix so it won't even find the template in a theme.

**Comment by tungnxt89** [comment]
Hi Polybear-Philippe,

> get_template_directory() only returns the Theme not a child theme so you cannot put the template in the child theme
We added the [commit](https://github.com/LearnPress/learnpress/commit/bbeeb17af573fcd5da65afa07b30b3045ca3b131).

> file_exists call doesn't really work as the template_name doesn't have a ".php" suffix so it won't even find the template in a theme.
The file_exists function checks whether a file or directory exists. So you don't need to include the ".php" extension because the [get_template] function checks for it. 

Thanks for the feedback.
