### ISSUE TITLE
The "Start Now" button is seen only on mouse over 

### ISSUE THREAD

**Issue by shrikantmulik** [LearnPress/learnpress#533]
When the course page gets displayed, the “Start Now” button is not seen since both the text color and background color seem to be same. It is a big UX issue that the blank box is seen when the user visits the page. Only on mouse hover, the background color changes to the primary color and the button is seen. Can this UX issue be fixed?

**Comment by tungnxt89** [comment]
Hi shrikantmulik,

Yes, we see that with the default theme of WP. We'll fix it on the LP version 4.2.1

Thanks.
