### ISSUE TITLE
Quizz is not translate

### ISSUE THREAD

**Issue by lchantemesse** [LearnPress/learnpress#535]
Translation doesn't take into account for string contained in quiz.js.
load like this :  (0,_wordpress_i18n__WEBPACK_IMPORTED_MODULE_2__.__)('Time spent', 'learnpress')

**Comment by tungnxt89** [comment]
Hi lchantemesse,

Yes, it is only in the file quiz.min.js.

Thanks.

**Comment by lchantemesse** [comment]
Thanks,

So what is the way to take into account quiz.min.js instead of quiz.js ?

**Comment by tungnxt89** [comment]
Hi lchantemesse,

To make LP load file quiz.min.js you need disable "Debug Mode" on the LernPress/Settings/Advanced

Thanks.

**Comment by lchantemesse** [comment]
Hi,

The translation contained in learnpress.po is not take into account for the quizz.min.js.

**Comment by tungnxt89** [comment]
Hi,

On the file learnpress.po, it contains text config translate of file quiz.min.js like the image https://freeimage.host/i/HEce8Kv

Thanks.

**Comment by lchantemesse** [comment]
Yes I found text to translate, but this transation is not take into account for js file only.

**Comment by tungnxt89** [comment]
Hi lchantemesse,

Can you provide us with info on your site? You can send info to email: tungnx@templatica.net
We'll check it.

Thanks
