### ISSUE TITLE
Conflicts with Wordpress Zeever theme

### ISSUE THREAD

**Issue by hongliangW** [LearnPress/learnpress#537]
`Learnpress` plugin possibly has a conflict with `Zeever` theme since once `Learnpress` is activated single page's content cannot be displayed. 

I am new to `Learnpress`, please let me know if you need more info to fix it. Thanks!

**Comment by tungnxt89** [comment]
Hi hongliangW,

We'll check it and then feedback for you.

Thanks.

**Comment by tungnxt89** [comment]
Hi hongliangW,

Oh, the theme Zeever is building with Gutenberg. Currently, LP is incompatible with the theme Gutenberg, we're fixing that soon.

Thank so much.

**Comment by hongliangW** [comment]
@tungnxt89 thank you! Do you have the ETA fix release date? I'm kind of in the middle of publishing the Wordpress website. Any workaround I can apply locally first to bypass this blocker? Thanks!

**Comment by hongliangW** [comment]
Any update on this issue? Thanks.

**Comment by tungnxt89** [comment]
Hi hongliangW,

We're developing beta v4.2.2.4, which includes compatibility with the Gutenberg theme. It is still in testing and has some bugs, which we're trying hard to fix and release soon. When we have done, we'll reply to you.

Thanks.

**Comment by tungnxt89** [comment]
Hi hongliangW,

We deploy the beta version to WP.org, you can [download it here](https://downloads.wordpress.org/plugin/learnpress.4.2.2.4.zip) to test and feedback to us, please send us image errors and description.

Thanks.

**Comment by hongliangW** [comment]
@tungnxt89 Thank you for confirming that. The issue has been fixed, thank you!
