### ISSUE TITLE
 Fatal error: Uncaught Error: Cannot use object of type LP_Profile_Tab as array

### ISSUE THREAD

**Issue by backstageel** [LearnPress/learnpress#540]
When trying to view the profile page I got the following error, using the last version of the plugin:

 Fatal error: Uncaught Error: Cannot use object of type LP_Profile_Tab as array in /home2/rede3net/public_html/wp-content/plugins/learnpress/inc/class-lp-query.php on line 267

**Comment by tungnxt89** [comment]
Hi backstageel,

What is the version LP you installed on your site?

Can you send me the Admin info site via mail: tungnxt89@gmail.com with the subject: "Cannot use object of type LP_Profile_Tab"
We'll check it.

Thanks.
