### ISSUE TITLE
Conflict with Bookingpress plugin

### ISSUE THREAD

**Issue by vodkaflip** [LearnPress/learnpress#543]
The learnpress plugin corrupts the admin interface of the [Bookingpress plugin.](https://wordpress.org/plugins/bookingpress-appointment-booking/) It seems that learnpress loads its CSS/JS on each admin page, even the ones that do not involve learnpress? Can this be looked into as it seems likely to cause corruption with other plugins as well?

**Comment by tungnxt89** [comment]
Hi vodkaflip,

We'll install that plugin and check. When we have done, we'll reply to you.

Thanks.
