### ISSUE TITLE
LearnPress 4.2.2.3 not loading lessons

### ISSUE THREAD

**Issue by RossCollicutt** [LearnPress/learnpress#544]
I'm was setting up a course with LearnPress last year and it was working great. I then deleted the plugin as I had other projects to do and then reinstalled it last month. All the content is still there but I can't add a lesson to any courses. The spinning icon just sits there when I try to add a lesson to a course. All editing on individual lessons or courses work. 

I've tried to disable all plugins, caching and the theme but it still does it. I can't find any errors in the debug log. Any ideas?

**Comment by tungnxt89** [comment]
Hi RossCollicutt,

We think your issues like [https://github.com/LearnPress/learnpress/issues/526](https://github.com/LearnPress/learnpress/issues/526)

If not, please send us some images, or send us the info on your site to tungnx@templatica.net. We'll check it.

Thanks.

**Comment by RossCollicutt** [comment]
Thanks @tungnxt89. It looks very similar. I will email you and update this thread if we can find a resolution so others may benefit.

**Comment by tungnxt89** [comment]
Hi RossCollicutt,

We think you should install a new site (staging site) with install new WordPress. Then install the lastest version of LearnPress.

Thanks.

**Comment by RossCollicutt** [comment]
I'm unable to set up a brand new site for this right now. Is there no way to properly remove everything from the plugin? Looks like it leaves a lot around when it's deleted and that's causing problems when reinstalling. Worked great when I installed the first time.

**Comment by RossCollicutt** [comment]
I deleted all the files from the plugin folder, removed all the tables from the database, and deleted all the options from the options table in the database. 

This causes the Quick setup to run again. 

All my old courses and lessons are still there? Where are courses and lessons stored? If we can't remove all of it, it's going to be very difficult to start again from scratch.

**Comment by tungnxt89** [comment]
Hi RossCollicutt,

You can try the plugin "Advanced WordPress Reset" to reset all.

Thanks.
