### ISSUE TITLE
Spelling is wrong "false"

### ISSUE THREAD

**Issue by AlladinKhan9** [LearnPress/learnpress#548]
https://github.com/LearnPress/learnpress/blob/4d16553ef14ab63a4c4b8218b824036f7d3209e9/inc/jwt/rest-api/version1/class-lp-rest-quiz-v1-controller.php#L395

**Comment by tungnxt89** [comment]
Hi AlladinKhan9,

Thanks for the feedback, we fixed it on [acd4322](https://github.com/LearnPress/learnpress/commit/acd43224321e3bcbde2364defebdfa531216f0c5)
