### ISSUE TITLE
Spelling is wrong "false"

### ISSUE THREAD

**Issue by AlladinKhan9** [LearnPress/learnpress#549]
https://github.com/LearnPress/learnpress/blob/4d16553ef14ab63a4c4b8218b824036f7d3209e9/inc/jwt/rest-api/version1/class-lp-rest-lessons-v1-controller.php#L333

**Comment by tungnxt89** [comment]
Hi

We replied on the topic [548](https://github.com/LearnPress/learnpress/issues/548)

Thank so much.
