### ISSUE TITLE
Wrong user enrollment status returned by plugin (maybe cache problem)

### ISSUE THREAD

**Issue by rajaeinet** [LearnPress/learnpress#551]
Hi,
I just updated to the latest version. (from v4.2.1.1 to v4.2.2.4)
In previous versions, I used the following method to check whether a user is enrolled in a course or not:
```
$coures_id = 144;  // example id
if( learn_press_get_user(get_current_user_id())->has_enrolled_course( $course_id ) ){
    // show something
}
```
But this method return false for new enrolled users now!
I've checked the database, we have an enrollment row in `learnpress_user_items` like the below image:

![2023-06-30_163754](https://github.com/LearnPress/learnpress/assets/89868505/174ab332-d543-4ad3-8c90-1cf2be65eccc)

**I'm developing my custom register integration. This integration add a user item row (like above) in learnpress_user_items table to enroll a new student in a specific lp course.**

All new enrolled users can't see the course content also! (learnpress default template codes are used here)

### Potential problem:
It seems that the problem is with the user item data cache!
The `has_enrolled_course()` method (in `inc/user/class-lp-user.php`) uses `get_course_data()` from `inc/user/abstract-lp-user.php`.
In this method, we call `get_last_user_course()` on an instance of `inc/database/class-lp-user-items-db.php`.
We use a LP_User_Items_Cache object to access data instantly In the method body. I mean the line no.338:
```
$result = $lp_user_items_cache->get_user_item( $key_cache );
```
The `$result` for new users is **null**. If we remove this line and next condition (below code), the bug will be fixed, because it will check the enrollment status from database directly.

https://github.com/LearnPress/learnpress/blob/4be67e5fda84f929e40d4f8b6625fbdef6da0aac/inc/databases/class-lp-user-items-db.php#L340-L343

I tested this problem on another raw wordpress and had the same problem. This bug seems to be related to the plugin.
@tungnxt89 , any idea? 🤔 

Thanks

**Comment by rajaeinet** [comment]
Hello
Can I clear the user item cache after placing an order?
I add an user item (to `learnpress-user-items` table) by myself to register the user into a course. Is there a way to delete the user item cache (or clear this new lesson key - like `UID/COURSE_ID/lp_course`) so it can be recreated?

My problem reason is that the `get_cache()` method (in the below code) returns null.
https://github.com/LearnPress/learnpress/blob/58ac43a2753c7b0820a2b6a7be9c4a00f0301616/inc/cache/class-lp-user-items-cache.php#L27-L38

Thanks

**Comment by tungnxt89** [comment]
Hi rajaeinet,

You can use the method "clean_user_item" to clear that cache
https://github.com/LearnPress/learnpress/blame/58ac43a2753c7b0820a2b6a7be9c4a00f0301616/inc/cache/class-lp-user-items-cache.php#L40

We will use to clean cache on "learn_press_update_user_item_field" and "delete_user_items_old". You should use hook custom, instead of writing your own, it can potentially errors and inconsistent flow.

Thanks.

**Comment by rajaeinet** [comment]
Hi
I used the `learn_press_update_user_item_field()` function in my learnpress addon. This function handle all things and also the cache. 😃 
https://github.com/LearnPress/learnpress/blob/a0272f2a09dc3847737c5241f27d70452036eba1/inc/user/lp-user-functions.php#L372-L390
This problem was fixed some time ago, but this issue has remained open!
Thanks for your help
