### ISSUE TITLE
Course Section Completed empty

### ISSUE THREAD

**Issue by aminshoukat** [LearnPress/learnpress#553]
In 
Learnpress -> inc -> course -> class-lp-course-section.php

you put that code:
```
	public function get_completed_items( $user_id = 0 ) {
		$items = array();
		return $items;
	}
```
Returning empty array? Doesn't make sense
Please fix this.

**Comment by tungnxt89** [comment]
Hi aminshoukat,

Yes, currently LearnPress not use that function for anywhere, we'll remove it soon.

Thanks.
