### ISSUE TITLE
Invalid Paypal Checkout Url after enabling Use PayPal REST API (Recommendations)

### ISSUE THREAD

**Issue by iofolle** [LearnPress/learnpress#565]
Hi, the Use PayPal REST API (Recommendations) does not work if currency is in EURO. In checkout when click on pay with paypal i've got 2Invalid Paypal Checkout Url". Debugging this on Paypal logs i discover that you sent price in the right currency (EURO) but in wrong notation, switching point with commas (EUR 1.000,00 is ok, EUR 1,000.00 give error). Could you check this?
Thanks

**Comment by iofolle** [comment]
Forgot to paste Paypal API error details:

Issue: INVALID_PARAMETER_SYNTAX
Description: Request is not well-formed, syntactically incorrect, or violates schema.

**Request:**
{
  "intent": "CAPTURE",
  "payment_source": {
    "paypal": {
      "experience_context": {
        "brand_name": "xxx",
        "cancel_url": "https://xxx",
        "landing_page": "LOGIN",
        "payment_method_preference": "UNRESTRICTED",
        "return_url": "https://xxx/lp-checkout/lp-order-received/1575?key=ORDER65xxx&paypay_express_checkout=1",
        "user_action": "PAY_NOW"
      }
    }
  },
  "purchase_units": [
    {
      "amount": {
        "currency_code": "EUR",
        "value": "2,000.00" <---- should be 2.000,00
      },
      "custom_id": 1575
    }
  ]
}

**Response:**

{
  "debug_id": "dfb1510292ce9",
  "details": [
    {
      "description": "The value of a field does not conform to the expected format.",
      "field": "/purchase_units/@reference_id=='default'/amount/value",
      "issue": "INVALID_PARAMETER_SYNTAX",
      "location": "body",
      "value": "xxxxxx"
    }
  ],
  "links": [
    {
      "encType": "xxxxxx",
      "href": "https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_PARAMETER_SYNTAX",
      "rel": "information_link"
    }
  ],
  "message": "Request is not well-formed, syntactically incorrect, or violates schema.",
  "name": "INVALID_REQUEST"
}

**Comment by tungnxt89** [comment]
Hi iofolle

We fixed it on the [v4.2.6.2-beta](https://downloads.wordpress.org/plugin/learnpress.4.2.6.2.zip). Can you download to test then feedback us.

Thanks.
