### ISSUE TITLE
Learnpress removes wordpress avatar classes.

### ISSUE THREAD

**Issue by divineproclamation** [LearnPress/learnpress#566]
Hi,

The learnpress plugin removes standard WordPress avatar classes. 

`<img alt="User Avatar" src="http://yourwebsite.com/wp-content/uploads/learn-press-profile/1/e1f6c13aa2e0a9e18fa6dbd5b384bccd.jpeg" height="250" width="250">`

This piece of html was retrieved by the `get_avatar()` function.

See it suppose to have the `.avatar` class, but it's missing. If deactivate the learnpress plugin, it works fine. So perhaps, look into the matter. 

Thanks in advance. It's a great plugin.

Cheers!

**Comment by divineproclamation** [comment]
<img width="1293" alt="Screenshot 2024-02-23 at 11 03 51 PM" src="https://github.com/LearnPress/learnpress/assets/97110057/8fd25513-5fb5-48c2-88a9-e65144705739">

See this screenshot from eduma theme.

**Comment by tungnxt89** [comment]
Hi divineproclamation,

LearnPress not rewrite function get avatar of Wordpress, it custom for self. So why LP need that class?

Thanks.
