### ISSUE TITLE
LearnPress Certificates

### ISSUE THREAD

**Issue by MedElevus** [LearnPress/learnpress#578]
I have an issue related to LearnPress Certificates plugin,
First of all, I purchased it but can't install it by the purchased code and it shows a message of error ....
Second of them, I tried to download the zip file and upload through the add new plugin but it shows incompatible zip file.
The last option I have is to upload directly to my file manager and unzip it, then I activate it from WordPress plugins and start to customize my settings. It worked but I face two issues.

The first issue when I enter any course the certificate can't previewed (attached image 1) instead of courses pages shows them (image 2)
The second issue is when I tried to test it on a real course and clicked on certificate button after complete the course it shows blank page (image three) instead of in settings it shows the certificates correctly (image four)
![image](https://github.com/user-attachments/assets/1e9699c1-c4d6-4664-86fb-32dd9c9c4a99)
![image](https://github.com/user-attachments/assets/fb430ac7-b269-4ba7-acda-9ed9b77d4296)
![image](https://github.com/user-attachments/assets/880a1c8b-336c-4f56-b36e-d34564ed0a20)
![image](https://github.com/user-attachments/assets/c5964907-96e5-406e-9a6b-b586ae535322)

**Comment by oanpamen** [comment]
Hola, tengo el mismo problema como lo solucionaste??
