### ISSUE TITLE
Correct Answers and Retakes

### ISSUE THREAD

**Issue by kkidudley** [LearnPress/LearnPress#78]
Having an issue with quizes. First issue is that if a user trys to retake the quiz it acts funny, sometimes will not let the user choose answers. Second is at the end of the quiz they do not see what questions they missed, i have chosen it to do so. Please help!

**Comment by haihld58** [comment]
Hello kkidudley,

Please update Learnpress 2.0.9 and check this issue again.

**Comment by kkidudley** [comment]
I would like a refund, how do I get one processed? 

 

Regards,
 
Kevin Dudley
Best Choice Recruiting
Toll Free | (877) 595-6185 ext. 501   Phone | (319) 382-8919    Fax | (515) 318-6085
