### ISSUE TITLE
Retake Quiz issue 2.0.9

### ISSUE THREAD

**Issue by smartie19889** [LearnPress/LearnPress#82]
Hi

When a user fails a quiz and clicks retake it refreshes the page and says "Your quiz grade failed. Quiz requirement 100%" not giving the user the opportunity to reanswer the questions.

Any ideas?

Thanks

**Comment by haihld58** [comment]
Hello smartie19889,

Please update latest version of Learnpress and check this issue again.

**Comment by smartie19889** [comment]
Hi. Sorry for the delay.

I have just updated to the latest version 2.1.2 and the issue is still there.

Thanks
